descripcion="ATAJOS DE TECLADO EN WINDOWS - RELACIÓN Nº 4: Atajos del navegador";
// Es la relación 4 de atajos Windows

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='Abrir nueva pestaña ';respuestas[n]='Control + T';n++;
preguntas[n]='Cerrar pestaña actual ';respuestas[n]='Control + W';n++;
preguntas[n]='Cerrar pestaña actual (alternativo) ';respuestas[n]='Control + F4';n++;
preguntas[n]='Reabrir pestaña cerrada ';respuestas[n]='Control + Mayus + T';n++;
preguntas[n]='Abrir ventana nueva ';respuestas[n]='Control + N';n++;
preguntas[n]='Abrir ventana nueva en modo privado ';respuestas[n]='Control + Mayus + N';n++;
preguntas[n]='Actualizar página ';respuestas[n]='F5';n++;
preguntas[n]='Forzar recarga completa ';respuestas[n]='Control + F5';n++;
preguntas[n]='Detener carga ';respuestas[n]='Esc';n++;
preguntas[n]='Ir a la barra de direcciones ';respuestas[n]='Control + L';n++;
preguntas[n]='Ir a la barra de direcciones (Alternativo) ';respuestas[n]='Alt + D';n++;
preguntas[n]='Abrir historial ';respuestas[n]='Control + H';n++;
preguntas[n]='Abrir descargas ';respuestas[n]='Control + J';n++;
preguntas[n]='Abrir marcadores ';respuestas[n]='Control + Mayus + O';n++;
preguntas[n]='Marcar página (añadirla a marcadores) ';respuestas[n]='Control + D';n++;
preguntas[n]='Abrir administrador de tareas ';respuestas[n]='Control + Mayus + Esc';n++;
preguntas[n]='Cambiar a pestaña siguiente ';respuestas[n]='Control + Tab';n++;
preguntas[n]='Cambiar a pestaña anterior ';respuestas[n]='Control + Mayus + Tab';n++;
preguntas[n]='Ir a pestaña 1 ';respuestas[n]='Control + 1';n++;
preguntas[n]='Ir a pestaña 2 ';respuestas[n]='Control + 2';n++;
preguntas[n]='Ir a pestaña 3 (... y así sucesivamente) ';respuestas[n]='Control + 3';n++;
preguntas[n]='Ir a última pestaña ';respuestas[n]='Control + 9';n++;
preguntas[n]='Buscar en la página ';respuestas[n]='Control + F';n++;
preguntas[n]='Abrir herramientas de desarrollo ';respuestas[n]='F12';n++;
preguntas[n]='Abrir menú/contexto del navegador (varía por navegador) ';respuestas[n]='Alt + E';n++;
preguntas[n]='Abrir menú/contexto del navegador (otro, varía por navegador) ';respuestas[n]='Alt + F';n++;
preguntas[n]='Ir arriba de la página ';respuestas[n]='Inicio';n++;
preguntas[n]='Ir abajo de la página ';respuestas[n]='Fin';n++;
preguntas[n]='Desplazar una pantalla hacia abajo ';respuestas[n]='AvPag';n++;
preguntas[n]='Desplazar una pantalla hacia arriba ';respuestas[n]='RePag';n++;
preguntas[n]='Ampliar zoom ';respuestas[n]='Control + +';n++;
preguntas[n]='Reducir zoom ';respuestas[n]='Control + -';n++;
preguntas[n]='Restablecer zoom ';respuestas[n]='Control + 0';n++;
preguntas[n]='Abrir enlace en pestaña nueva ';respuestas[n]='Control + clic';n++;
preguntas[n]='Abrir enlace en ventana nueva ';respuestas[n]='Mayus + clic';n++;
preguntas[n]='Abrir búsqueda en pestaña nueva ';respuestas[n]='Alt + Intro';n++;
preguntas[n]='Volver a la página anterior ';respuestas[n]='Alt + FlechaIzq';n++;
preguntas[n]='Avanzar a la página siguiente ';respuestas[n]='Alt + FlechaDch';n++;
preguntas[n]='Ir a inicio de la barra de direcciones ';respuestas[n]='Control + FlechaIzq';n++;
preguntas[n]='Ir al final de la barra de direcciones ';respuestas[n]='Control + FlechaDch';n++;
