relacion=1; // Para mostrar al principio de la página: Relación nº...

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='Mostrar un mensaje "Hola" en una ventana emergente ';respuestas[n]='alert("Hola")';n++;
preguntas[n]='Preguntar al usuario ¿Cómo te llamas? y guardar la respuesta en una variable llamada nombre ';respuestas[n]='nombre=prompt("¿Cómo te llamas?")';n++;
preguntas[n]='Mostrar un saludo "Hola" seguido del nombre del usuario anterior ';respuestas[n]='alert("Hola "+nombre)';n++;
preguntas[n]='Obtener la longitud de la cadena nombre y guardarla en una variable llamada n ';respuestas[n]='n=nombre.length';n++;
preguntas[n]='Guardar el primer carácter de nombre en una variable llamada caracter ';respuestas[n]='caracter=nombre[0]';n++;
preguntas[n]='Guardar el segundo carácter de nombre en caracter ';respuestas[n]='caracter=nombre[1]';n++;
preguntas[n]='Guardar el tercer carácter de nombre en caracter ';respuestas[n]='caracter=nombre[2]';n++;
preguntas[n]='Guardar el último carácter de nombre en caracter ';respuestas[n]='caracter=nombre[n-1]';n++;
preguntas[n]='Eliminar espacios al inicio y al final de nombre ';respuestas[n]='nombre=nombre.trim()';n++;
preguntas[n]='Convertir nombre a mayúsculas ';respuestas[n]='nombre=nombre.toUpperCase()';n++;
preguntas[n]='Convertir nombre a minúsculas ';respuestas[n]='nombre=nombre.toLowerCase()';n++;
preguntas[n]='Preguntar "Dime tu apellido" y guardarlo en una variable llamada apellido ';respuestas[n]='apellido=prompt("Dime tu apellido")';n++;
preguntas[n]='Crear una cadena completa con nombre y apellido y guardarla en una variable llamada completo ';respuestas[n]='completo=nombre+" "+apellido';n++;
preguntas[n]='Mostrar el nombre completo ';respuestas[n]='alert(completo)';n++;
preguntas[n]='Preguntar "Dime un número" y convertirlo a tipo numérico usando multiplicación por 1, guardarlo en una variable llamada a ';respuestas[n]='a=1*prompt("Dime un número")';n++;
preguntas[n]='Preguntar "Dime otro número" y convertirlo a tipo numérico, guardarlo en una variable llamada b ';respuestas[n]='b=1*prompt("Dime otro número")';n++;
preguntas[n]='Sumar a y b, guardar en en una variable llamada c ';respuestas[n]='c=a+b';n++;
preguntas[n]='Mostrar el resultado de la suma anterior ';respuestas[n]='alert(c)';n++;
preguntas[n]='Mostrar la suma con mensaje "La suma es" (deja un espacio) ';respuestas[n]='alert("La suma es "+c)';n++;
preguntas[n]='Restar a menos b, guardar en c ';respuestas[n]='c=a-b';n++;
preguntas[n]='Multiplicar a por b, guardar en c ';respuestas[n]='c=a*b';n++;
preguntas[n]='Dividir a entre b, guardar en c ';respuestas[n]='c=a/b';n++;
preguntas[n]='Dividir a entre b y convertir a entero, guardar en c ';respuestas[n]='c=parseInt(a/b)';n++;
preguntas[n]='Obtener el resto de dividir a entre b, guardar en c ';respuestas[n]='Javascript 2ºBach';n++;
preguntas[n]='Elevar a a la potencia b, guardar en c ';respuestas[n]='c=a**b';n++;
preguntas[n]='Obtener un número aleatorio entre 0 y 1 y guardarlo en una variable llamada x ';respuestas[n]='x=Math.random()';n++;
preguntas[n]='Obtener un número aleatorio entre 0 y 100 y guardarlo en x (resultado con decimales) ';respuestas[n]='x=100*Math.random()';n++;
preguntas[n]='Obtener un número ENTERO aleatorio entre 0 y 100 y guardarlo en x ';respuestas[n]='x=parseInt(100*Math.random())';n++;
preguntas[n]='Simular un lanzamiento de dado y guardar en x ';respuestas[n]='x=1+parseInt(6*Math.random())';n++;
preguntas[n]='Preguntar al usuario "Dime tu nota en el examen", convertir a número y guardar en una variable llamada nota ';respuestas[n]='nota=1*prompt("Dime tu nota en el examen")';n++;
preguntas[n]='Mostrar "Aprobado/a" si nota es mayor o igual a 5 ';respuestas[n]='if(nota>=5) alert("Aprobado/a")';n++;
preguntas[n]='Continuando con lo anterior, en caso contrario mostrar "Suspenso/a" ';respuestas[n]='else alert("Suspenso/a")';n++;
preguntas[n]='¿Qué hay que escribir delante de un texto para convertirlo en comentario? ';respuestas[n]='//';n++;
preguntas[n]='¿Qué hay que escribir encima de un conjunto de líneas para convertir todas ellas en comentario? ';respuestas[n]='/*';n++;
preguntas[n]='¿Qué hay que escribir por debajo de la última línea del bloque de comentario? ';respuestas[n]='*/';n++;
preguntas[n]='Mostrar un mensaje "Bienvenidos/as" en una ventana emergente ';respuestas[n]='alert("Bienvenidos/as")';n++;
preguntas[n]='Preguntar al usuario ¿Cuántos años tienes? y guardar el dato introducido en una variable llamada edad (es un dato numérico) ';respuestas[n]='edad=1*prompt("¿Cuántos años tienes?")';n++;
preguntas[n]='Hacer lo mismo que lo anterior considerando ahora que la edad se ha introducido en un objeto INPUT cuyo ID es entrada1 ';respuestas[n]='edad=1*entrada1.value';n++;
preguntas[n]='Mostrar un mensaje emergente diciendo "Tienes X años", usando la variable edad ';respuestas[n]='alert("Tienes "+edad+" años")';n++;
preguntas[n]='Mostrar el mismo mensaje anterior pero en este caso enviado a la misma página, forzando un salto de línea final ';respuestas[n]='document.write("Tienes "+edad+" años<br>")';n++;
preguntas[n]='Preguntar al usuario ¿Cómo te llamas? y guardarlo en una variable llamada nombre ';respuestas[n]='nombre=prompt("¿Cómo te llamas?")';n++;
preguntas[n]='Hacer lo mismo que lo anterior considerando ahora que el nombre se ha escrito en un objeto INPUT cuyo ID es entrada2 ';respuestas[n]='nombre=entrada2.value';n++;
preguntas[n]='Guardar en una variable longitudNombre la longitud de la cadena que representa el nombre ';respuestas[n]='longitudNombre=nombre.length';n++;
preguntas[n]='Guardar la primera letra del nombre en una variable llamada primeraLetra ';respuestas[n]='primeraLetra=nombre[0]';n++;
preguntas[n]='Guardar la última letra del nombre en una variable llamada ultimaLetra ';respuestas[n]='Javascript 2ºBach';n++;
preguntas[n]='Preguntar al usuario ¿En qué ciudad naciste? y guardar la respuesta en una variable llamada ciudad ';respuestas[n]='ciudad=prompt("¿En qué ciudad naciste?")';n++;
preguntas[n]='Convertir el nombre de la ciudad a mayúsculas ';respuestas[n]='ciudad=ciudad.toUpperCase()';n++;
preguntas[n]='Convertir el nombre de la ciudad a minúsculas ';respuestas[n]='ciudad=ciudad.toLowerCase()';n++;
preguntas[n]='Eliminar espacios al inicio y al final de la variable ciudad ';respuestas[n]='ciudad=ciudad.trim()';n++;
preguntas[n]='Crear una variable llamada mensaje que combine "Hola", el nombre y la ciudad, separadas por comas y dejando un espacio después de cada coma ';respuestas[n]='mensaje="Hola, "+nombre+", "+ciudad';n++;
preguntas[n]='Mostrar el valor de la variable anterior en una ventana emergente ';respuestas[n]='alert(mensaje)';n++;
preguntas[n]='Mostrar el mensaje anterior enviado a la propia página, forzando un salto final de línea ';respuestas[n]='document.write(mensaje+"<br>")';n++;
preguntas[n]='Preguntar al usuario Dime un número y guardarlo en una variable llamada num1 ';respuestas[n]='num1=1*prompt("Dime un número")';n++;
preguntas[n]='Preguntar al usuario Dime otro número y guardarlo en una variable llamada num2 ';respuestas[n]='num2=1*prompt("Dime otro número")';n++;
preguntas[n]='Calcular la suma de num1 y num2 y guardarla en una variable suma ';respuestas[n]='suma=num1+num2';n++;
preguntas[n]='Mostrar la suma en ventana emergente: "El resultado de la suma es" ';respuestas[n]='alert("El resultado de la suma es "+suma)';n++;
preguntas[n]='Mostrar el mensaje anterior enviado a la propia página, forzando un salto final de línea ';respuestas[n]='document.write("El resultado de la suma es "+suma+"<br>")';n++;
preguntas[n]='Calcular la resta, multiplicación y división exacta de num1 y num2, guardando cada resultado en respectivamente en las variables resta, producto y division (sin tilde) ';respuestas[n]='resta=num1-num2;producto=num1*num2;division=num1/num2';n++;
preguntas[n]='Calcular la división entera de num1 entre num2 y guardarla en una variable llamada cociente ';respuestas[n]='cociente=parseInt(num1/num2)';n++;
preguntas[n]='Calcular el resto de dividir num1 entre num2 y guardarlo en una variable llamada resto ';respuestas[n]='resto=num1%num2';n++;
preguntas[n]='Elevar num1 a la potencia num2 y guardarlo en una variable llamada potencia ';respuestas[n]='potencia=num1**num2';n++;
preguntas[n]='Generar un número aleatorio en el intervalo [0,1) y guardarlo en una variable llamada rand ';respuestas[n]='rand=Math.random()';n++;
preguntas[n]='Generar un número aleatorio (con decimales) en el intervalo [0,50) y guardarlo en rand ';respuestas[n]='rand=50*Math.random()';n++;
preguntas[n]='Generar un número entero aleatorio entre 1 y 50 y guardarlo en rand ';respuestas[n]='rand=1+parseInt(50*Math.random())';n++;
preguntas[n]='Generar un número entero aleatorio entre 0 y 1 y guardarlo en una variable llamada moneda ';respuestas[n]='moneda=parseInt(2*Math.random())';n++;
preguntas[n]='Mostrar "Cara" o "Cruz" dependiendo del valor obtenido en la sentencia anterior (dos sentencias en la misma línea) ';respuestas[n]='if(moneda==0) alert("Cara");else alert("Cruz")';n++;
preguntas[n]='Repetir lo anterior en una sola sentencia ';respuestas[n]='if(moneda==0){alert("Cara")}else{alert("Cruz")}';n++;
preguntas[n]='Preguntar al usuario "Dime tu nota de examen" y guardarla en una variable llamada notaExamen ';respuestas[n]='notaExamen=1*prompt("Dime tu nota de examen")';n++;
preguntas[n]='Mostrar ventana emergente "Aprobado" o "Suspenso" dependiendo de dicha nota (dos sentencias en la misma línea) ';respuestas[n]='if(notaExamen>=5) alert("Aprobado");else alert("Suspenso")';n++;
preguntas[n]='Repetir lo anterior en una sola sentencia ';respuestas[n]='if(notaExamen>=5){alert("Aprobado")}else{alert("Suspenso")}';n++;
preguntas[n]='Preguntar al usuario ¿Cuál es tu bebida favorita? y guardarla en una variable llamada bebida ';respuestas[n]='bebida=prompt("¿Cuál es tu bebida favorita?")';n++;
preguntas[n]='Mostrar un mensaje que diga "Tu bebida favorita es X", usando la variable bebida de la línea anterior ';respuestas[n]='alert("Tu bebida favorita es "+bebida)';n++;
preguntas[n]='Preguntar al usuario una palabra (variable palabra1) ';respuestas[n]='palabra1=prompt("Dime una palabra")';n++;
preguntas[n]='Preguntar al usuario otra palabra (variable palabra2) ';respuestas[n]='palabra2=prompt("Dime otra palabra")';n++;
preguntas[n]='Crear una nueva variable llamada combinada que encadene las dos palabras anteriores separadas por un guion ';respuestas[n]='combinada=palabra1+"-"+palabra2';n++;
preguntas[n]='Una variable llamada x toma un valor introducido por el usuario en ventana emergente (Dime un número) ';respuestas[n]='x=1*prompt("Dime un número")';n++;
preguntas[n]='Código para mostrar el texto emergente Positivo o Negativo dependiendo del valor de x (no usar punto y coma, usar llaves) ';respuestas[n]='if(x>=0){alert("Positivo")}else{alert("Negativo")}';n++;
preguntas[n]='Repetir el código anterior para que ejecute exactamente lo mismo usando la condición inversa ';respuestas[n]='if(x<0){alert("Negativo")}else{alert("Positivo")}';n++;
preguntas[n]='Una variable llamada a toma el valor numérico de un objeto INPUT cuyo ID es entrada1 ';respuestas[n]='a=1*entrada1.value';n++;
preguntas[n]='Otra variable llamada b toma el valor numérico de un objeto INPUT cuyo ID es entrada2 ';respuestas[n]='b=1*entrada2.value';n++;
preguntas[n]='Una variable llamada c toma el cociente de la división entera de a entre b (variables anteriores) ';respuestas[n]='c=parseInt(a/b)';n++;
preguntas[n]='Mostrar, dependiendo de las tres variables anteriores, el texto emergente que ves en la pizarra ';respuestas[n]='alert("La división entera de "+a+" entre "+b+" es "+c)';n++;
preguntas[n]='Una variable llamada resto toma el resto de la división de a entre b (variables anteriores) ';respuestas[n]='resto=a%b';n++;
preguntas[n]='Mostrar, dependiendo de las variables anteriores, el texto emergente que ves en la pizarra ';respuestas[n]='alert("El resto de dividir "+a+" entre "+b+" es "+resto)';n++;
preguntas[n]='Repetir el mensaje anterior directamente en la página, sin ventaba emergente ';respuestas[n]='document.write("El resto de dividir "+a+" entre "+b+" es "+resto)';n++;
preguntas[n]='Código para mostrar, dependiendo del texto anterior, uno de los dos textos emergentes que ves en la pizarra (no usar punto y coma, usar llaves) ';respuestas[n]='if(resto==0){alert(a+" ES múltiplo de "+b)}else{alert(a+" NO es múltiplo de "+b)}';n++;
preguntas[n]='Bucle for para repetir un código 100 veces, con una variable i que va tomando valores a partir del cero. Preguntar al profesor. ';respuestas[n]='for(i=0;i<100;i=i+1){//Código}';n++;
preguntas[n]='Repetir el código anterior con autoincremento de i (así lo haremos a partir de ahora) ';respuestas[n]='for(i=0;i<100;i++){//Código}';n++;
preguntas[n]='Bucle for para repetir un código 100 veces, con una variable i que va tomando valores desde 99 hasta 0 ';respuestas[n]='for(i=99;i>=0;i=i-1){//Código}';n++;
preguntas[n]='Repetir el código anterior con autodecremento de i (así lo haremos a partir de ahora) ';respuestas[n]='for(i=99;i>=0;i--){//Código}';n++;
preguntas[n]='Bucle while para repetir un código mientras una variable llamada texto sea distinto de FIN ';respuestas[n]='while(texto!="FIN"){//Código}';n++;
preguntas[n]='Repetir el código anterior para que el bucle finalice cuando el valor sea FIN, Fin, fin, fiN, etc.  ';respuestas[n]='while(texto.toUpperCase()!="FIN"){//Código}';n++;
preguntas[n]='Definir un array llamado provincias con los valores granada, almería y jaén (en este orden) ';respuestas[n]='provincias=new Array("granada","almería","jaén")';n++;
preguntas[n]='Asignar el valor málaga en la siguiente posición del array ';respuestas[n]='provincias[3]="málaga"';n++;
preguntas[n]='Asignar el valor córdoba en la siguiente posición del array ';respuestas[n]='provincias[4]="córdoba"';n++;
preguntas[n]='Asignar el valor cádiz en la siguiente posición del array ';respuestas[n]='provincias[5]="cádiz"';n++;
preguntas[n]='Asignar el valor huelva en la siguiente posición del array ';respuestas[n]='provincias[6]="huelva"';n++;
preguntas[n]='Asignar el valor sevilla en la siguiente posición del array ';respuestas[n]='provincias[7]="sevilla"';n++;
preguntas[n]='Teniendo en cuenta lo anterior ¿Qué valor devuelve provincias.length ? ';respuestas[n]='8';n++;
preguntas[n]='En el array anterior ¿Existe el elemento provincias[8] ? ';respuestas[n]='No';n++;
preguntas[n]='¿Qué valor devuelve el acceso anterior? (y en general cualquier acceso a una posición inexistente) ';respuestas[n]='undefined';n++;
preguntas[n]='Definir un array vacío llamado instituto ';respuestas[n]='instituto=new Array()';n++;
preguntas[n]='Suponiendo que instituto ha sido rellenado con los nombres de todos los estudiantes, definir una variable n que toma la cantidad total de elementos. ';respuestas[n]='n=instituto.length';n++;
preguntas[n]='Usando la variable anterior, escribe el código para mostrar todos los alumnos/as, cada uno de ellos en ventana emergente (Del primero al último) ';respuestas[n]='for(i=0;i<n;i++){alert(instituto[i])}';n++;
preguntas[n]='Repite el código anterior para mostrarlos en la página sin ventanas emergentes, dejando un salto de línea detrás de cada nombre ';respuestas[n]='for(i=0;i<n;i++){document.write(instituto[i]+"<br>")}';n++;
preguntas[n]='Repite el código anterior para mostrarlos en orden inverso (del último al primero) ';respuestas[n]='for(i=n-1;i>=0;i--){document.write(instituto[i]+"<br>")}';n++;
preguntas[n]='Buscar el alumno llamado Natalio (es un texto, no una variable) en el array anterior, hallar la posición que ocupa en una variable llamada pos ';respuestas[n]='pos=instituto.indexOf("Natalio")';n++;
preguntas[n]='En la búsqueda anterior ¿Qué valor toma pos si no existe dicho alumno en el array? ';respuestas[n]='-1';n++;
preguntas[n]='Si en el array hay varios elementos con el mismo texto buscado ¿Qué valor tomaría pos en la búsqueda anterior? (Pregunta a tu profesor) ';respuestas[n]='La posición del primero que encuentre';n++;
preguntas[n]='Una variable llamada cadena toma un texto introducido en un objeto INPUT cuyo ID es entrada1 ';respuestas[n]='cadena=entrada1.value';n++;
preguntas[n]='Quitar los espacios laterales de la cadena del ejercicio anterior ';respuestas[n]='cadena=cadena.trim()';n++;
preguntas[n]='Definir un array llamado conjunto que tome tantos elementos como textos separados mediante comas contenga la cadena anterior ';respuestas[n]='conjunto=cadena.split(",")';n++;
preguntas[n]='Definir una variable n que calcule la cantidad de elementos del array creado en el ejercicio anterior ';respuestas[n]='n=conjunto.length';n++;
preguntas[n]='Código para quitar los espacios laterales de cada uno de los elementos del array anterior (conjunto). Utiliza un bucle for creciente, variable i ';respuestas[n]='for(i=0;i<n;i++){conjunto[i]=conjunto[i].trim()}';n++;
preguntas[n]='Código para mostrar en ventanas emergentes cada uno de los elementos del conjunto anterior y el número de caracteres de cada uno de ellos (Dos sentencias en el interior del bucle for) ';respuestas[n]='for(i=0;i<n;i++){alert(conjunto[i]);alert(conjunto[i].length)}';n++;
