descripcion="REPRESENTACIÓN INTERNA EN DISPOSITIVOS DIGITALES - EJERCICIOS Y CUESTIONES - RELACIÓN Nº 8 - Representación de imágenes (mapas de bits)";
// Es la relación 8 de ejercicios de tipo Decimal-Binario, concepto de byte, múltiplos, etc.
// ¿Rellenar este comentario?

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='¿Qué es un mapa de bits? ';respuestas[n]='Es un formato de imagen que utiliza una cuadrícula de píxeles para representar imágenes';n++;
preguntas[n]='Los archivos de imagen pueden ser de varios tipos: PNG, JPG, GIF... ¿Qué extensión tienen los archivos de mapa de bits? ';respuestas[n]='BMP';n++;
preguntas[n]='¿Qué es un píxel? ';respuestas[n]='Es cada uno de los puntos individuales de una imagen';n++;
preguntas[n]='En JSPaint ¿se puede dibujar píxel a píxel con detalle, con el Zoom ampliado al máximo? ';respuestas[n]='Sí';n++;
preguntas[n]='En un mapa de bits (archivo BMP) ¿qué espacio en disco ocupa cada píxel? ';respuestas[n]='3 bytes';n++;
preguntas[n]='¿Qué determina el primero de esos tres bytes? ';respuestas[n]='El nivel de rojo';n++;
preguntas[n]='¿Qué determina el segundo de esos tres bytes? ';respuestas[n]='El nivel de verde';n++;
preguntas[n]='¿Qué determina el tercero de esos tres bytes? ';respuestas[n]='El nivel de azul';n++;
preguntas[n]='¿A qué menú de JSPaint debemos acceder para establecer con precisión las dimensiones del lienzo? ';respuestas[n]='Imagen-Atributos';n++;
preguntas[n]='Escribe el atajo de teclado correspondiente a la operación anterior ';respuestas[n]='Ctrl+E';n++;
preguntas[n]='El lienzo de un archivo BMP tiene una anchura de 300 píxeles y una altura de 400 píxeles. ¿Cuántos píxeles en total contiene el dibujo? ';respuestas[n]='120000';n++;
preguntas[n]='¿Cuantos bytes ocupa en disco el archivo correspondiente? ';respuestas[n]='360000';n++;
preguntas[n]='Escribe dicha cantidad expresada en KB con dos decimales. ';respuestas[n]='351.56';n++;
preguntas[n]='¿Qué es RGB? ';respuestas[n]='Es un formato que representa cada color mediante un código de tres bytes';n++;
preguntas[n]='Escribe el código RGB del negro (tres números en formato decimal) ';respuestas[n]='RGB(0,0,0)';n++;
preguntas[n]='Escribe el código del negro en formato hexadecimal (seis cifras) ';respuestas[n]='#000000';n++;
preguntas[n]='Escribe el código del negro en binario (24 bits separados en cuartetos) ';respuestas[n]='0000 0000 0000 0000 0000 0000';n++;
preguntas[n]='Escribe la fórmula que permite determinar cuántos colores distintos existen utilizando el código RGB. ';respuestas[n]='256*256*256';n++;
preguntas[n]='Escribe el resultado de dicha fórmula. Obtienes así la cantidad total de colores. ';respuestas[n]='16777216';n++;
preguntas[n]='Un archivo BMP tiene una imagen totalmente blanca ¿Qué valor tienen todos sus bytes binarios? (8 bits) ';respuestas[n]='1111 1111';n++;
preguntas[n]='Un archivo BMP tiene una imagen totalmente negra ¿Qué valor tienen todos sus bytes binarios? (8 bits) ';respuestas[n]='0000 0000';n++;
preguntas[n]='CONSULTA LOS SIGUIENTES COLORES EN LA PALETA DE JSPaint<br>Escribe el código del color Blanco en formato RGB decimal ';respuestas[n]='RGB(255,255,255)';n++;
preguntas[n]='Escribe el código del color Blanco en formato hexadecimal ';respuestas[n]='#FFFFFF';n++;
preguntas[n]='Escribe el código del color Negro en formato RGB decimal ';respuestas[n]='RGB(0,0,0)';n++;
preguntas[n]='Escribe el código del color Negro en formato hexadecimal ';respuestas[n]='#000000';n++;
preguntas[n]='Escribe el código del color Plata en formato RGB decimal ';respuestas[n]='RGB(192,192,192)';n++;
preguntas[n]='Escribe el código del color Plata en formato hexadecimal ';respuestas[n]='#C0C0C0';n++;
preguntas[n]='Escribe el código del color Gris medio en formato RGB decimal ';respuestas[n]='RGB(128,128,128)';n++;
preguntas[n]='Escribe el código del color Gris medio en formato hexadecimal ';respuestas[n]='#808080';n++;
preguntas[n]='Escribe el código del color Rojo en formato RGB decimal ';respuestas[n]='RGB(255,0,0)';n++;
preguntas[n]='Escribe el código del color Rojo en formato hexadecimal ';respuestas[n]='#FF0000';n++;
preguntas[n]='Escribe el código del color Rojo oscuro en formato RGB decimal ';respuestas[n]='RGB(128,0,0)';n++;
preguntas[n]='Escribe el código del color Rojo oscuro en formato hexadecimal ';respuestas[n]='#800000';n++;
preguntas[n]='Escribe el código del color Amarillo en formato RGB decimal ';respuestas[n]='RGB(255,255,0)';n++;
preguntas[n]='Escribe el código del color Amarillo en formato hexadecimal ';respuestas[n]='#FFFF00';n++;
preguntas[n]='Escribe el código del color Oliva en formato RGB decimal ';respuestas[n]='RGB(128,128,0)';n++;
preguntas[n]='Escribe el código del color Oliva en formato hexadecimal ';respuestas[n]='#808000';n++;
preguntas[n]='Escribe el código del color Verde en formato RGB decimal ';respuestas[n]='RGB(0,255,0)';n++;
preguntas[n]='Escribe el código del color Verde en formato hexadecimal ';respuestas[n]='#00FF00';n++;
preguntas[n]='Escribe el código del color Verde oscuro en formato RGB decimal ';respuestas[n]='RGB(0,128,0)';n++;
preguntas[n]='Escribe el código del color Verde oscuro en formato hexadecimal ';respuestas[n]='#008000';n++;
preguntas[n]='Escribe el código del color Cian claro en formato RGB decimal ';respuestas[n]='RGB(0,255,255)';n++;
preguntas[n]='Escribe el código del color Cian claro en formato hexadecimal ';respuestas[n]='#00FFFF';n++;
preguntas[n]='Escribe el código del color Cian oscuro en formato RGB decimal ';respuestas[n]='RGB(0,128,128)';n++;
preguntas[n]='Escribe el código del color Cian oscuro en formato hexadecimal ';respuestas[n]='#008080';n++;
preguntas[n]='Escribe el código del color Azul en formato RGB decimal ';respuestas[n]='RGB(0,0,255)';n++;
preguntas[n]='Escribe el código del color Azul en formato hexadecimal ';respuestas[n]='#0000FF';n++;
preguntas[n]='Escribe el código del color Azul oscuro en formato RGB decimal ';respuestas[n]='RGB(0,0,128)';n++;
preguntas[n]='Escribe el código del color Azul oscuro en formato hexadecimal ';respuestas[n]='#000080';n++;
preguntas[n]='Escribe el código del color Magenta claro en formato RGB decimal ';respuestas[n]='RGB(255,0,255)';n++;
preguntas[n]='Escribe el código del color Magenta claro en formato hexadecimal ';respuestas[n]='#FF00FF';n++;
preguntas[n]='Escribe el código del color Magenta oscuro en formato RGB decimal ';respuestas[n]='RGB(128,0,128)';n++;
preguntas[n]='Escribe el código del color Magenta oscuro en formato hexadecimal ';respuestas[n]='#800080';n++;
preguntas[n]='Escribe el código del color Amarillo claro en formato RGB decimal ';respuestas[n]='RGB(255,255,128)';n++;
preguntas[n]='Escribe el código del color Amarillo claro en formato hexadecimal ';respuestas[n]='#FFFF80';n++;
preguntas[n]='MÁS CUESTIONES<br>En JSPaint ¿cómo se invierten los colores de la imagen? (Cada píxel invierte su color y se obtiene el "negativo" de la imagen) ';respuestas[n]='Imagen-Invertir colores';n++;
preguntas[n]='Escribe el atajo de teclado correspondiente a la operación anterior ';respuestas[n]='Ctrl+I';n++;
preguntas[n]='En un código RGB expresado en binario (24 bits) ¿cómo se halla el código del color inverso? ';respuestas[n]='Invirtiendo cada uno de los bits';n++;
preguntas[n]='¿Cuál sería el código inverso del color binario siguiente? 1010 1100 0101 1101 1110 0010 ';respuestas[n]='0101 0011 1010 0010 0001 1101';n++;
preguntas[n]='Si el código de un color es RGB(x,y,z) ¿Cuál es el código del color inverso? ';respuestas[n]='RGB(255-x,255-y,255-z)';n++;
preguntas[n]='¿Cuál es el código inverso de un color cuyo código en decimal es el siguiente? RGB(85,120,240) ';respuestas[n]='RGB(170,135,15)';n++;
preguntas[n]='¿Cuál es el código inverso de un color cuyo código en hexadecimal es el siguiente? #2F6A8C ';respuestas[n]='#D09573';n++;
