descripcion="REPRESENTACIÓN INTERNA EN DISPOSITIVOS DIGITALES - EJERCICIOS Y CUESTIONES - RELACIÓN Nº 5";
// Es la relación 5 de ejercicios de tipo Decimal-Binario, concepto de byte, múltiplos, etc.
// Paso de decimal a binario (divisiones entre 2)

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='<br>PASO DE DECIMAL A BINARIO</b><br>Escribe el valor decimal del número propuesto en clase: ';respuestas[n]='13';n++;
preguntas[n]='Resto de dividir 13 entre 2 =  ';respuestas[n]='1';n++;
preguntas[n]='13 / 2 = ';respuestas[n]='6';n++;
preguntas[n]='Resto de dividir 6 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='6 / 2 = ';respuestas[n]='3';n++;
preguntas[n]='Resto de dividir 3 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='3 / 2 = ';respuestas[n]='1';n++;
preguntas[n]='Escribe el número 13 en binario (Forma básica) ';respuestas[n]='1101';n++;
preguntas[n]='Escribe el byte correspondiente en binario, dejando un espacio entre los dos cuartetos de bits ';respuestas[n]='0000 1101';n++;
preguntas[n]='Escribe el byte correspondiente en hexadecimal (dos cifras) ';respuestas[n]='0D';n++;
preguntas[n]='<br><b>NUEVO NÚMERO</b><br>Escribe el valor decimal del número propuesto en clase: ';respuestas[n]='22';n++;
preguntas[n]='Resto de dividir 22 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='22 / 2 = ';respuestas[n]='11';n++;
preguntas[n]='Resto de dividir 11 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='11 / 2 = ';respuestas[n]='5';n++;
preguntas[n]='Resto de dividir 5 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='5 / 2 = ';respuestas[n]='2';n++;
preguntas[n]='Resto de dividir 2 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='2 / 2 = ';respuestas[n]='1';n++;
preguntas[n]='Escribe el número 22 en binario (Forma básica) ';respuestas[n]='10110';n++;
preguntas[n]='Escribe el byte correspondiente en binario, dejando un espacio entre los dos cuartetos de bits ';respuestas[n]='0001 0110';n++;
preguntas[n]='Escribe el byte correspondiente en hexadecimal (dos cifras) ';respuestas[n]='16';n++;
preguntas[n]='<br><b>NUEVO NÚMERO</b><br>Escribe el valor decimal del número propuesto en clase: ';respuestas[n]='50';n++;
preguntas[n]='Resto de dividir 50 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='50 / 2 = ';respuestas[n]='25';n++;
preguntas[n]='Resto de dividir 25 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='25 / 2 = ';respuestas[n]='12';n++;
preguntas[n]='Resto de dividir 12 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='12 / 2 = ';respuestas[n]='6';n++;
preguntas[n]='Resto de dividir 6 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='6 / 2 = ';respuestas[n]='3';n++;
preguntas[n]='Resto de dividir 3 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='3 / 2 = ';respuestas[n]='1';n++;
preguntas[n]='Escribe el número 50 en binario (Forma básica) ';respuestas[n]='110010';n++;
preguntas[n]='Escribe el byte correspondiente en binario, dejando un espacio entre los dos cuartetos de bits ';respuestas[n]='0011 0010';n++;
preguntas[n]='Escribe el byte correspondiente en hexadecimal (dos cifras) ';respuestas[n]='32';n++;
preguntas[n]='<br><b>NUEVO NÚMERO</b><br>Escribe el valor decimal del número propuesto en clase: ';respuestas[n]='73';n++;
preguntas[n]='Resto de dividir 73 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='73 / 2 = ';respuestas[n]='36';n++;
preguntas[n]='Resto de dividir 36 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='36 / 2 = ';respuestas[n]='18';n++;
preguntas[n]='Resto de dividir 18 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='18 / 2 = ';respuestas[n]='9';n++;
preguntas[n]='Resto de dividir 9 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='9 / 2 = ';respuestas[n]='4';n++;
preguntas[n]='Resto de dividir 4 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='4 / 2 = ';respuestas[n]='2';n++;
preguntas[n]='Resto de dividir 2 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='2 / 2 = ';respuestas[n]='1';n++;
preguntas[n]='Escribe el número 73 en binario (Forma básica) ';respuestas[n]='1001001';n++;
preguntas[n]='Escribe el byte correspondiente en binario, dejando un espacio entre los dos cuartetos de bits ';respuestas[n]='0100 1001';n++;
preguntas[n]='Escribe el byte correspondiente en hexadecimal (dos cifras) ';respuestas[n]='49';n++;
preguntas[n]='<br><b>NUEVO NÚMERO</b><br>Escribe el valor decimal del número propuesto en clase: ';respuestas[n]='175';n++;
preguntas[n]='Resto de dividir 175 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='175 / 2 = ';respuestas[n]='87';n++;
preguntas[n]='Resto de dividir 87 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='87 / 2 = ';respuestas[n]='43';n++;
preguntas[n]='Resto de dividir 43 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='43 / 2 = ';respuestas[n]='21';n++;
preguntas[n]='Resto de dividir 21 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='21 / 2 = ';respuestas[n]='10';n++;
preguntas[n]='Resto de dividir 10 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='10 / 2 = ';respuestas[n]='5';n++;
preguntas[n]='Resto de dividir 5 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='5 / 2 = ';respuestas[n]='2';n++;
preguntas[n]='Resto de dividir 2 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='2 / 2 = ';respuestas[n]='1';n++;
preguntas[n]='Escribe el número 175 en binario (Forma básica) ';respuestas[n]='10101111';n++;
preguntas[n]='Escribe el byte correspondiente en binario, dejando un espacio entre los dos cuartetos de bits ';respuestas[n]='1010 1111';n++;
preguntas[n]='Escribe el byte correspondiente en hexadecimal (dos cifras) ';respuestas[n]='AF';n++;
preguntas[n]='<br><b>NUEVO NÚMERO</b><br>Escribe el valor decimal del número propuesto en clase: ';respuestas[n]='212';n++;
preguntas[n]='Resto de dividir 212 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='212 / 2 = ';respuestas[n]='106';n++;
preguntas[n]='Resto de dividir 106 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='106 / 2 = ';respuestas[n]='53';n++;
preguntas[n]='Resto de dividir 53 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='53 / 2 = ';respuestas[n]='26';n++;
preguntas[n]='Resto de dividir 26 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='26 / 2 = ';respuestas[n]='13';n++;
preguntas[n]='Resto de dividir 13 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='13 / 2 = ';respuestas[n]='6';n++;
preguntas[n]='Resto de dividir 6 entre 2 = ';respuestas[n]='0';n++;
preguntas[n]='6 / 2 = ';respuestas[n]='3';n++;
preguntas[n]='Resto de dividir 3 entre 2 = ';respuestas[n]='1';n++;
preguntas[n]='3 / 2 = ';respuestas[n]='1';n++;
preguntas[n]='Escribe el número 212 en binario (Forma básica) ';respuestas[n]='11010100';n++;
preguntas[n]='Escribe el byte correspondiente en binario, dejando un espacio entre los dos cuartetos de bits ';respuestas[n]='1101 0100';n++;
preguntas[n]='Escribe el byte correspondiente en hexadecimal (dos cifras) ';respuestas[n]='D4';n++;
preguntas[n]='<br>RECUERDA - De forma ya directa: Escribe el byte binario correspondiente al valor decimal 255 ';respuestas[n]='1111 1111';n++;
preguntas[n]='¿Cuál es su valor en hexadecimal? ';respuestas[n]='FF';n++;
preguntas[n]='Escribe el byte binario correspondiente al valor decimal 254 ';respuestas[n]='1111 1110';n++;
preguntas[n]='¿Cuál es su valor hexadecimal? ';respuestas[n]='FE';n++;
preguntas[n]='Escribe, ya todo en hexadecimal, el valor anterior (que en decimal es 253) ';respuestas[n]='FD';n++;
preguntas[n]='Escribe el valor hexadecimal anterior ';respuestas[n]='FC';n++;
preguntas[n]='Escribe el valor hexadecimal anterior ';respuestas[n]='FB';n++;
preguntas[n]='Escribe el valor hexadecimal anterior ';respuestas[n]='FA';n++;
preguntas[n]='Escribe el valor hexadecimal anterior ';respuestas[n]='F9';n++;
preguntas[n]='Escribe el valor hexadecimal anterior ';respuestas[n]='F8';n++;
preguntas[n]='Escribe el valor hexadecimal anterior ';respuestas[n]='F7';n++;
preguntas[n]='<b>Última pregunta:</b>Escribe el valor hexadecimal anterior ';respuestas[n]='F6';n++;

