descripcion="REPRESENTACIÓN INTERNA EN DISPOSITIVOS DIGITALES - EJERCICIOS Y CUESTIONES - RELACIÓN Nº 6 - Bytes y múltiplos del byte";
// Es la relación 6 de ejercicios de tipo Decimal-Binario, concepto de byte, múltiplos, etc.
// ¿Rellenar este comentario?

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='<b>TEORÍA - CUESTIONES INICIALES:<b><br>¿Qué es un byte? ';respuestas[n]='La unidad básica de almacenamiento formada por 8 bits';n++;
preguntas[n]='¿Por qué el byte se considera una unidad pequeña? ';respuestas[n]='Porque puede almacenar muy poca información';n++;
preguntas[n]='¿Por qué se usan múltiplos del byte? ';respuestas[n]='Para medir cantidades mayores de información de forma más cómoda';n++;
preguntas[n]='¿Cuántos bytes tiene 1 KB? ';respuestas[n]='1 KB tiene 1024 bytes';n++;
preguntas[n]='¿Qué significa “kilo” en informática? ';respuestas[n]='Significa 1024, no 1000';n++;
preguntas[n]='¿3 KB son 3000 bytes? ';respuestas[n]='No, 3 KB=3*1024=3072 bytes';n++;
preguntas[n]='¿Cuántos KB tiene 1 MB? ';respuestas[n]='1 MB tiene 1024 KB';n++;
preguntas[n]='¿1 MB es un millón de bytes? ';respuestas[n]='No exactamente, es 1048576 bytes';n++;
preguntas[n]='¿Cuántos MB tiene 1 GB? ';respuestas[n]='1 GB tiene 1024 MB';n++;
preguntas[n]='¿Por qué se usa 1024 y no 1000 en Informática? ';respuestas[n]='Porque 1024 es 2 elevado a 10';n++;
preguntas[n]='¿Cuántos KB tiene un GB? ';respuestas[n]='1048576';n++;
preguntas[n]='¿Cuántos bytes tiene un GB? ';respuestas[n]='1073741824';n++;
preguntas[n]='¿Cuántos GB tiene un TB? ';respuestas[n]='1024';n++;
preguntas[n]='¿Cuántos MB tiene un TB? ';respuestas[n]='1048576';n++;
preguntas[n]='¿Cuántos KB tiene un TB? ';respuestas[n]='1073741824';n++;
preguntas[n]='¿Cuántos bytes tiene un TB? ';respuestas[n]='1099511627776';n++;
preguntas[n]='<br><b>PROBLEMA 1:</b><br>¿Cuál es la unidad de almacenamiento más grande que aparece en el problema? ';respuestas[n]='GB';n++;
preguntas[n]='¿Cuál es la unidad de almacenamiento más pequeña que aparece en el problema? ';respuestas[n]='MB';n++;
preguntas[n]='Convierte el tamaño del disco duro a MB (Escribe directamente el resultado) ';respuestas[n]='30720';n++;
preguntas[n]='Escribe la operación que permite calcular cuántas fotos caben en el disco duro (ya todo en las mismas unidades) ';respuestas[n]='30720/3';n++;
preguntas[n]='Escribe el número total de fotos que se pueden almacenar (el resultado de la operación anterior) ';respuestas[n]='10240';n++;
preguntas[n]='<br><b>PROBLEMA 2:</b><br>¿Cuál es la unidad de almacenamiento más grande que aparece en el problema? ';respuestas[n]='GB';n++;
preguntas[n]='¿Cuál es la unidad de almacenamiento más pequeña que aparece en el problema? ';respuestas[n]='MB';n++;
preguntas[n]='Convierte el tamaño de la tarjeta SD a MB (Escribe directamente el resultado) ';respuestas[n]='8192';n++;
preguntas[n]='Escribe la operación que permite calcular cuántas canciones caben en la tarjeta (ya todo en las mismas unidades) ';respuestas[n]='2298199';n++;
preguntas[n]='Escribe el número total de canciones que se pueden almacenar (el resultado de la operación anterior) ';respuestas[n]='2048';n++;
preguntas[n]='<br><b>PROBLEMA 3:</b><br>¿Cuál es la unidad de almacenamiento más grande que aparece en el problema? ';respuestas[n]='GB';n++;
preguntas[n]='¿Cuál es la unidad de almacenamiento más pequeña que aparece en el problema? ';respuestas[n]='KB';n++;
preguntas[n]='Convierte el tamaño del DVD a KB (Escribe directamente el resultado) ';respuestas[n]='4194304';n++;
preguntas[n]='Escribe la operación que permite calcular cuántas películas caben en el DVD (ya todo en las mismas unidades) ';respuestas[n]='4194304/524288';n++;
preguntas[n]='Escribe el número total de películas que se pueden almacenar (el resultado de la operación anterior) ';respuestas[n]='8';n++;
preguntas[n]='<br><b>PROBLEMA 4:</b><br>¿Cuál es la unidad de almacenamiento más grande que aparece en el problema? ';respuestas[n]='MB';n++;
preguntas[n]='¿Cuál es la unidad de almacenamiento más pequeña que aparece en el problema? ';respuestas[n]='KB';n++;
preguntas[n]='Convierte el tamaño del disco duro a KB (Escribe directamente el resultado) ';respuestas[n]='512000000';n++;
preguntas[n]='Escribe la operación que permite calcular cuántos documentos caben en el disco (ya todo en las mismas unidades) ';respuestas[n]='512000000/2048';n++;
preguntas[n]='Escribe el número total de documentos que se pueden almacenar (el resultado de la operación anterior) ';respuestas[n]='250000';n++;
preguntas[n]='<br><b>PROBLEMA 5:</b><br>¿Cuál es la unidad de almacenamiento más grande que aparece en el problema? ';respuestas[n]='GB';n++;
preguntas[n]='¿Cuál es la unidad de almacenamiento más pequeña que aparece en el problema? ';respuestas[n]='KB';n++;
preguntas[n]='Convierte el tamaño de la tarjeta SD a KB (Escribe directamente el resultado) ';respuestas[n]='33554432';n++;
preguntas[n]='Escribe la operación que permite calcular cuántas fotos caben en la tarjeta (ya todo en las mismas unidades) ';respuestas[n]='33554432/8192';n++;
preguntas[n]='Escribe el número total de fotos que se pueden almacenar (el resultado de la operación anterior) ';respuestas[n]='4096';n++;
preguntas[n]='<br><b>PROBLEMA 6:</b><br>¿Cuál es la unidad de almacenamiento más grande que aparece en el problema? ';respuestas[n]='TB';n++;
preguntas[n]='¿Cuál es la unidad de almacenamiento más pequeña que aparece en el problema? ';respuestas[n]='GB';n++;
preguntas[n]='Convierte el tamaño del disco duro a GB (Escribe directamente el resultado) ';respuestas[n]='1024';n++;
preguntas[n]='Escribe la operación que permite calcular cuántos archivos caben en el disco (ya todo en las mismas unidades) ';respuestas[n]='-319920';n++;
preguntas[n]='Escribe el número total de archivos que se pueden almacenar (el resultado de la operación anterior) ';respuestas[n]='512';n++;
preguntas[n]='<br><b>PROBLEMA 7:</b><br>¿Cuál es la unidad de almacenamiento más grande que aparece en el problema? ';respuestas[n]='TB';n++;
preguntas[n]='¿Cuál es la unidad de almacenamiento más pequeña que aparece en el problema? ';respuestas[n]='MB';n++;
preguntas[n]='Convierte el tamaño del disco duro a MB (Escribe directamente el resultado) ';respuestas[n]='2097152';n++;
preguntas[n]='Escribe la operación que permite calcular cuántas películas caben en el disco (ya todo en las mismas unidades) ';respuestas[n]='2097152/1024';n++;
preguntas[n]='Escribe el número total de películas que se pueden almacenar (el resultado de la operación anterior) ';respuestas[n]='2048';n++;
preguntas[n]='<br><b>PROBLEMA 8:</b><br>¿Cuál es la unidad de almacenamiento más grande que aparece en el problema? ';respuestas[n]='GB';n++;
preguntas[n]='¿Cuál es la unidad de almacenamiento más pequeña que aparece en el problema? ';respuestas[n]='MB';n++;
preguntas[n]='Convierte el tamaño de la tarjeta SD a MB (Escribe directamente el resultado) ';respuestas[n]='65536';n++;
preguntas[n]='Escribe la operación que permite calcular cuántas canciones caben en la tarjeta (ya todo en las mismas unidades) ';respuestas[n]='65536/16';n++;
preguntas[n]='Escribe el número total de canciones que se pueden almacenar (el resultado de la operación anterior) ';respuestas[n]='4096';n++;
preguntas[n]='<br><b>PROBLEMA 9:</b><br>¿Cuál es la unidad de almacenamiento más grande que aparece en el problema? ';respuestas[n]='TB';n++;
preguntas[n]='¿Cuál es la unidad de almacenamiento más pequeña que aparece en el problema? ';respuestas[n]='MB';n++;
preguntas[n]='Convierte el tamaño del disco duro a MB (Escribe directamente el resultado) ';respuestas[n]='3145728';n++;
preguntas[n]='Escribe la operación que permite calcular cuántos archivos caben en el disco (ya todo en las mismas unidades) ';respuestas[n]='3145728/48';n++;
preguntas[n]='Escribe el número total de archivos que se pueden almacenar (el resultado de la operación anterior) ';respuestas[n]='65536';n++;
preguntas[n]='<br><b>PROBLEMA 10:</b><br>¿Cuál es la unidad de almacenamiento más grande que aparece en el problema? ';respuestas[n]='TB';n++;
preguntas[n]='¿Cuál es la unidad de almacenamiento más pequeña que aparece en el problema? ';respuestas[n]='KB';n++;
preguntas[n]='Convierte el tamaño del disco duro a KB (Escribe directamente el resultado) ';respuestas[n]='1073741824';n++;
preguntas[n]='Escribe la operación que permite calcular cuántos archivos caben en el disco (ya todo en las mismas unidades) ';respuestas[n]='1073741824/512';n++;
preguntas[n]='Escribe el número total de archivos que se pueden almacenar (el resultado de la operación anterior) ';respuestas[n]='2097152';n++;
