descripcion="REPRESENTACIÓN INTERNA EN DISPOSITIVOS DIGITALES - EJERCICIOS Y CUESTIONES - RELACIÓN Nº 7 - Representación de cadenas de texto";
// Es la relación 7 de ejercicios de tipo Decimal-Binario, concepto de byte, múltiplos, etc.
// ¿Rellenar este comentario?

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='¿Cuántos bytes ocupa en general una cadena de texto? (Consulta tus apuntes) ';respuestas[n]='Tantos como caracteres contenga';n++;
preguntas[n]='¿Cuántos bytes ocupa cada carácter individual? ';respuestas[n]='1';n++;
preguntas[n]='Cuando hablamos de caracteres ¿nos referimos sólo a letras? ';respuestas[n]='No';n++;
preguntas[n]='Las cifras numéricas ¿Son caracteres? ';respuestas[n]='Sí';n++;
preguntas[n]='¿Y los espacios en blanco? ';respuestas[n]='Sí';n++;
preguntas[n]='¿Y los puntos, comas, paréntesis, etc? ';respuestas[n]='Sí';n++;
preguntas[n]='¿Cómo se llama el código que asocia cada carácter a un número? ';respuestas[n]='ASCII';n++;
preguntas[n]='El código de una letra mayúscula ¿es el mismo que el de esa misma letra minúscula? ';respuestas[n]='No';n++;
preguntas[n]='¿Cuál es el código del espacio en blanco? ';respuestas[n]='32';n++;
preguntas[n]='¿Cómo es el bit binario correspondiente? ';respuestas[n]='0010 0000';n++;
preguntas[n]='¿Cuál es el código ASCII del carácter 0? ';respuestas[n]='48';n++;
preguntas[n]='¿Cómo es el bit binario correspondiente? (Muy distinto de la representación binaria del número 0) ';respuestas[n]='0011 0000';n++;
preguntas[n]='¿Cuál es el código ASCII de la letra A? ';respuestas[n]='65';n++;
preguntas[n]='¿Cuál es el código ASCII de la letra a? ';respuestas[n]='97';n++;
preguntas[n]='¿Cuántos bytes ocupa el siguiente texto? CR7 ';respuestas[n]='3';n++;
preguntas[n]='¿Cuántos bits ocupa dicho texto? ';respuestas[n]='24';n++;
preguntas[n]='¿Cuáles serían los códigos ASCII de dicho texto? (Escríbelos separados mediante espacio) ';respuestas[n]='67 82 55';n++;
preguntas[n]='¿Cómo es la representación binaria de dicho texto? (Separa los bits en cuartetos) ';respuestas[n]='0100 0011 0101 0010 0011 0111';n++;
preguntas[n]='¿Cuántos bytes ocupa el siguiente texto? Hola ¿Qué tal? ';respuestas[n]='14';n++;
preguntas[n]='¿Cuántos bits ocupa dicho texto? ';respuestas[n]='112';n++;
preguntas[n]='Escribe el primer byte binario de dicho texto ';respuestas[n]='0100 1000';n++;
preguntas[n]='Escribe el quinto byte binario de dicho texto ';respuestas[n]='0010 0000';n++;
preguntas[n]='Escribe el séptimo byte binario de dicho texto ';respuestas[n]='0101 0001';n++;
preguntas[n]='Escribe el séptimo byte binario de dicho texto ';respuestas[n]='0101 0001';n++;
preguntas[n]='Escribe el noveno byte binario de dicho texto ';respuestas[n]='0110 0101';n++;
preguntas[n]='Escribe el último byte binario de dicho texto ';respuestas[n]='0011 1111';n++;
preguntas[n]='Si escribes un dato en la calculadora ¿Cómo se procesa internamente, como número o como texto? ';respuestas[n]='Como número';n++;
preguntas[n]='Si escribes un dato en un editor de texto ¿Cómo se procesa internamente, como número o como texto? ';respuestas[n]='Como texto';n++;
preguntas[n]='Si el dato que escribes en el editor de texto contiene sólo cifras numéricas ¿Se procesa como número? ';respuestas[n]='No';n++;
preguntas[n]='Si escribes el dato CR7 en una celda de hoja de cálculo ¿Cómo se procesa internamente, como número o como texto? ';respuestas[n]='Como texto';n++;
preguntas[n]='¿Cuántos bytes ocupa el dato de la cuestión anterior? ';respuestas[n]='3';n++;
preguntas[n]='Si escribes el dato 26789 en una celda de hoja de cálculo ¿Cómo se procesa internamente, como número o como texto? ';respuestas[n]='Como número';n++;
preguntas[n]='¿Cuántos bytes ocupa el dato de la cuestión anterior? (Piensa por qué) ';respuestas[n]='4';n++;
preguntas[n]='Si escribes el dato 12 345 (Con un espacio) en una celda de hoja de cálculo ¿Cómo se procesa internamente, como número o como texto? ';respuestas[n]='Como texto';n++;
preguntas[n]='¿Cuántos bytes ocupa el dato de la cuestión anterior? (Piensa por qué) ';respuestas[n]='6';n++;
preguntas[n]='¿Cuántos bytes ocupa un número de teléfono de nueve cifras, si es considerado como texto? ';respuestas[n]='9';n++;
preguntas[n]='¿Y si es considerado como número? (Ya que todos sus caracteres son cifras numéricas) ';respuestas[n]='4';n++;
preguntas[n]='Un DNI de ocho cifras con letra al final ¿Qué tipo de dato es? ';respuestas[n]='Texto';n++;
preguntas[n]='¿Cuántos bytes ocupa? ';respuestas[n]='9';n++;
preguntas[n]='Una matrícula española (Ejemplo 1234 MDP) ¿Qué tipo de dato es? ';respuestas[n]='Texto';n++;
preguntas[n]='¿Cuántos bytes ocupa? ';respuestas[n]='8';n++;
preguntas[n]='¿Qué es el texto plano? (Consulta tus apuntes) ';respuestas[n]='Es el que tiene en cuenta únicamente los caracteres y no su formato';n++;
preguntas[n]='Un documento creado en el Bloc de Notas ¿es texto plano? ';respuestas[n]='Sí';n++;
preguntas[n]='Un documento creado en Microsoft Word ¿es texto plano? ';respuestas[n]='No';n++;
preguntas[n]='Un archivo de texto plano contiene 987654 caracteres. ¿Cuál es su tamaño en disco, medido en bytes? ';respuestas[n]='987654';n++;
preguntas[n]='Escribe la operación que permite hallar la cantidad anterior en kilobytes (KB) ';respuestas[n]='987654/1024';n++;
preguntas[n]='Escribe dicha cantidad (tamaño del archivo en KB, dos decimales) ';respuestas[n]='964.51';n++;
preguntas[n]='Escribe la operación que permite hallar la cantidad anterior en megabytes (MB) ';respuestas[n]='964.51/1024';n++;
preguntas[n]='Escribe dicha cantidad (tamaño del archivo en MB, dos decimales) ';respuestas[n]='0.94';n++;
preguntas[n]='Un archivo creado en Word con los mismos caracteres que el archivo anterior ¿Ocupa el mismo espacio en disco? (Piensa por qué) ';respuestas[n]='No';n++;
preguntas[n]='¿Ocupa más espacio o menos que el archivo de texto plano? ';respuestas[n]='Más';n++;
preguntas[n]='La tabla que ves en la pizarra ¿Cuántos registros tiene? (También puedes verla en la parte final de tus apuntes) ';respuestas[n]='12';n++;
preguntas[n]='¿Cuántos campos tiene cada registro? ';respuestas[n]='3';n++;
preguntas[n]='¿De qué tipo es el primer campo? ';respuestas[n]='Texto';n++;
preguntas[n]='¿Cuántos bytes ocupa? ';respuestas[n]='30';n++;
preguntas[n]='¿De qué tipo es el segundo campo? ';respuestas[n]='Texto';n++;
preguntas[n]='¿Cuántos bytes ocupa? ';respuestas[n]='10';n++;
preguntas[n]='¿De qué tipo es el tercer campo? ';respuestas[n]='Número';n++;
preguntas[n]='¿Cuántos bytes ocupa? ';respuestas[n]='1';n++;
preguntas[n]='¿Cuántos bytes ocupa cada registro completo de esta tabla? ';respuestas[n]='41';n++;
preguntas[n]='¿Cuántos bytes ocupa la tabla completa, con todos sus registros? ';respuestas[n]='492';n++;
preguntas[n]='Escribe la operación que permite hallar la cantidad anterior en kilobytes (KB) ';respuestas[n]='552/1024';n++;
preguntas[n]='Escribe dicha cantidad (dos decimales) ';respuestas[n]='0.48';n++;
