descripcion="REPRESENTACIÓN INTERNA EN DISPOSITIVOS DIGITALES - EJERCICIOS Y CUESTIONES - RELACIÓN Nº 2";
// Es la relación 2 de ejercicios de tipo Decimal-Binario, concepto de byte, múltiplos, etc.
// Sistema binario

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='¿Qué es un bit? ';respuestas[n]='Es la unidad binaria';n++;
preguntas[n]='¿Cuáles son los únicos valores de un bit? ';respuestas[n]='Cero y uno';n++;
preguntas[n]='¿Qué es un byte? (Unidad de almacenamiento digital) ';respuestas[n]='Un conjunto de ocho bits';n++;
preguntas[n]='Escribe el número decimal 6 representado en binario (de forma básica) ';respuestas[n]='110';n++;
preguntas[n]='Escribe el byte binario que representa el número decimal 6 ';respuestas[n]='00000110';n++;
preguntas[n]='Si añadimos ceros a la izquierda de una cadena de bits ¿Cambia su valor? ';respuestas[n]='No';n++;
preguntas[n]='Escribe el byte binario con valor más bajo posible (debes indicar todos los bits) ';respuestas[n]='00000000';n++;
preguntas[n]='¿A qué número en código decimal corresponde dicho byte? ';respuestas[n]='0';n++;
preguntas[n]='Escribe el byte binario con valor más alto posible ';respuestas[n]='11111111';n++;
preguntas[n]='¿A qué número en código decimal corresponde dicho byte? ';respuestas[n]='255';n++;
preguntas[n]='En un número escrito en binario ¿Qué bit hay que mirar para ver si es par o impar? ';respuestas[n]='El último';n++;
preguntas[n]='¿Qué valor tiene ese bit si el número es par? ';respuestas[n]='0';n++;
preguntas[n]='¿Qué valor tiene ese bit si el número es impar? ';respuestas[n]='1';n++;
preguntas[n]='Si un número binario N es representado en binario como ABCD0 ¿Cómo es N+1 en binario? <br>(A, B, C y D son bits) ';respuestas[n]='ABCD1';n++;
preguntas[n]='Si un número binario N es representado en binario como ABC01 ¿Cómo es N+1 en binario? ';respuestas[n]='ABC10';n++;
preguntas[n]='Si un número binario N es representado en binario como AB011 ¿Cómo es N+1 en binario? ';respuestas[n]='AB100';n++;
preguntas[n]='Si un número binario N es representado en binario como A0111 ¿Cómo es N+1 en binario? ';respuestas[n]='A1000';n++;
preguntas[n]='Si un número binario N es representado en binario como 11111 ¿Cómo es N+1 en binario? ';respuestas[n]='100000';n++;
preguntas[n]='Escribe el resultado de la potencia 2<sup>0</sup> ';respuestas[n]='1';n++;
preguntas[n]='Escribe el resultado de la potencia 2<sup>1</sup> ';respuestas[n]='2';n++;
preguntas[n]='Escribe el resultado de la potencia 2<sup>2</sup> ';respuestas[n]='4';n++;
preguntas[n]='Escribe el resultado de la potencia 2<sup>3</sup> ';respuestas[n]='8';n++;
preguntas[n]='Escribe el resultado de la potencia 2<sup>4</sup> ';respuestas[n]='16';n++;
preguntas[n]='Escribe el resultado de la potencia 2<sup>5</sup> ';respuestas[n]='32';n++;
preguntas[n]='Escribe el resultado de la potencia 2<sup>6</sup> ';respuestas[n]='64';n++;
preguntas[n]='Escribe el resultado de la potencia 2<sup>7</sup> ';respuestas[n]='128';n++;
preguntas[n]='Escribe el resultado de la potencia 2<sup>7</sup> ';respuestas[n]='256';n++;
preguntas[n]='En general, si 2 elevado a n es x ¿Cuánto es 2 elevado a n+1? ';respuestas[n]='x*2';n++;
preguntas[n]='Escribe la descomposición binaria completa del número binario 101, incluyendo todas las potencias y bits, y muestra el resultado decimal correspondiente ';respuestas[n]='1*4+0*2+1*1=5';n++;
preguntas[n]='Escribe la descomposición binaria completa del número binario 111010, incluyendo todas las potencias y bits, y muestra el resultado decimal correspondiente ';respuestas[n]='1*32+1*16+1*8+0*4+1*2+0*1=58';n++;
preguntas[n]='Repite el ejercicio anterior escribiendo sólo lo mínimo, sin indicar ya los bits (sólo las potencias de dos que deben sumarse) ';respuestas[n]='32+16+8+2=58';n++;
preguntas[n]='<b>Los ejercicios restantes debes hacerlos de la misma forma que el último</b><br>Deduce el valor decimal del número binario 111 ';respuestas[n]='4+2+1=7';n++;
preguntas[n]='Deduce el valor decimal del número binario 111 ';respuestas[n]='4+2+1=7';n++;
preguntas[n]='Deduce el valor decimal del número binario 1010 ';respuestas[n]='8+2=10';n++;
preguntas[n]='Deduce el valor decimal del número binario 10001 ';respuestas[n]='16+1=17';n++;
preguntas[n]='Deduce el valor decimal del número binario 11111 ';respuestas[n]='16+8+4+2+1=31';n++;
preguntas[n]='Deduce el valor decimal del número binario 100000 ';respuestas[n]='32=32';n++;
preguntas[n]='Deduce el valor decimal del número binario 101101 ';respuestas[n]='32+8+4+1=45';n++;
preguntas[n]='Deduce el valor decimal del número binario 1100000 ';respuestas[n]='64+32=96';n++;
preguntas[n]='Deduce el valor decimal del número binario 1111111 ';respuestas[n]='64+32+16+8+4+2+1=127';n++;
preguntas[n]='Deduce el valor decimal del número binario 10000000 ';respuestas[n]='128=128';n++;
preguntas[n]='Deduce el valor decimal del número binario 10011001 ';respuestas[n]='128+16+8+1=153';n++;
preguntas[n]='Deduce el valor decimal del número binario 11110000 ';respuestas[n]='128+64+32+16=240';n++;
preguntas[n]='Deduce el valor decimal del número binario 10101011 ';respuestas[n]='128+32+8+2+1=171';n++;
preguntas[n]='Deduce el valor decimal del número binario 11111111 ';respuestas[n]='128+64+32+16+8+4+2+1=255';n++;
preguntas[n]='Deduce el valor decimal del número binario 100000000 ';respuestas[n]='256=256';n++;
preguntas[n]='¿Cómo es en binario el número decimal 256? (Forma básica, sin ceros a la izquierda) ';respuestas[n]='100000000';n++;
preguntas[n]='¿Cuántos bytes ocupa dicho número? (Piensa por qué) ';respuestas[n]='2';n++;
preguntas[n]='Escribe dichos bytes, <b>dejando un espacio entre cada cuatro bits</b> para facilitar la lectura ';respuestas[n]='0000 0001 0000 0000';n++;
preguntas[n]='Escribe los bytes correspondientes al número decimal 257 (Respuesta similar a la anterior) ';respuestas[n]='0000 0001 0000 0001';n++;
preguntas[n]='Escribe los bytes correspondientes al número decimal 258 (Respuesta similar a la anterior) ';respuestas[n]='0000 0001 0000 0010';n++;
preguntas[n]='Escibe de nuevo el byte binario correspondiente al valor decimal 0, separando los dos cuartetos mediante un espacio (a partir de ahora lo haremos siempre así) ';respuestas[n]='0000 0000';n++;
preguntas[n]='Escibe de nuevo el byte binario correspondiente al valor decimal 255, separando los dos cuartetos mediante un espacio ';respuestas[n]='1111 1111';n++;
preguntas[n]='Escribe los bytes (separando cuartetos) del número binario 1111111111111111 (cadena con 16 unos) ';respuestas[n]='1111 1111 1111 1111';n++;
preguntas[n]='¿Cuántos bytes ocupa dicho número en binario? ';respuestas[n]='2';n++;
preguntas[n]='Escribe los bytes (separando cuartetos) del número binario <b>siguiente</b> al del ejercicio anterior (1111111111111111) ';respuestas[n]='0000 0001 0000 0000 0000 0000';n++;
preguntas[n]='¿Cuál es el valor decimal del número binario que acabas de responder? (Dedúcelo fácilmente y escribe directamente el resultado sin operaciones) ';respuestas[n]='65536';n++;
preguntas[n]='¿Cuántos bytes ocupa dicho número en binario? ';respuestas[n]='3';n++;
preguntas[n]='Teniendo en cuenta tus últimas respuestas, deduciéndolo fácilmente, ¿Cuál es el valor decimal del número binario 1111111111111111? ';respuestas[n]='65535';n++;
preguntas[n]='Si un número es potencia de dos ¿Cuántos "unos" hay en su correspondiente valor binario? ';respuestas[n]='1';n++;
preguntas[n]='¿Cuántos "ceros" hay en el valor binario de un número inmediatamente anterior a una potencia de dos? ';respuestas[n]='0';n++;
preguntas[n]='<br>Mira la tabla de equivalencias hexadecimales. ¿Cuántas cifras hexadecimales hay en un byte? ';respuestas[n]='2';n++;
preguntas[n]='¿Cuáles son las cifras hexadecimales? (Ya se preguntó esto otro día) ';respuestas[n]='0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal 3F ';respuestas[n]='0011 1111';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal B2 ';respuestas[n]='1011 0010';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal 7E ';respuestas[n]='0111 1110';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal 4C ';respuestas[n]='0100 1100';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal E7 ';respuestas[n]='1110 0111';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal 9A ';respuestas[n]='1001 1010';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal 2F ';respuestas[n]='0010 1111';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal D4 ';respuestas[n]='1101 0100';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal 6B ';respuestas[n]='0110 1011';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal 18 ';respuestas[n]='0001 1000';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal C7 ';respuestas[n]='1100 0111';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal 5E ';respuestas[n]='0101 1110';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal 3D ';respuestas[n]='0011 1101';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal 0F ';respuestas[n]='0000 1111';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal 4A ';respuestas[n]='0100 1010';n++;
preguntas[n]='Escribe el valor binario del byte hexadecimal FF ';respuestas[n]='1111 1111';n++;
preguntas[n]='<br><b>Ejercicios inversos a los anteriores:</b><br>Escribe el valor hexadecimal del byte binario 01111100 ';respuestas[n]='7C';n++;
preguntas[n]='Escribe el valor hexadecimal del byte binario 0000 0000 (la respuesta a este tipo de ejercicio siempre requiere dos cifras) ';respuestas[n]='00';n++;
preguntas[n]='Escribe el valor hexadecimal del byte binario 1010 1110 ';respuestas[n]='AE';n++;
preguntas[n]='Escribe el valor hexadecimal del byte binario 0010 0011 ';respuestas[n]='23';n++;
preguntas[n]='Escribe el valor hexadecimal del byte binario 1111 0001 ';respuestas[n]='F1';n++;
preguntas[n]='Escribe el valor hexadecimal del byte binario 0001 1001 ';respuestas[n]='19';n++;
preguntas[n]='El sistema hexadecimal se utiliza para... (Mira tus apuntes) ';respuestas[n]='facilitar la lectura de bytes binarios.';n++;
preguntas[n]='<br>¿Cuál sería el valor hexadecimal siguiente a 98? ';respuestas[n]='99';n++;
preguntas[n]='¿Y el siguiente? ';respuestas[n]='9A';n++;
preguntas[n]='¿Y el siguiente? ';respuestas[n]='9B';n++;
preguntas[n]='¿Y el siguiente? ';respuestas[n]='9C';n++;
preguntas[n]='¿Y el siguiente? ';respuestas[n]='9D';n++;
preguntas[n]='¿Y el siguiente? ';respuestas[n]='9E';n++;
preguntas[n]='¿Y el siguiente? ';respuestas[n]='9F';n++;
preguntas[n]='¿Y el siguiente? ';respuestas[n]='A0';n++;
preguntas[n]='¿Y el siguiente? ';respuestas[n]='A1';n++;
preguntas[n]='¿Y el siguiente? ';respuestas[n]='A2';n++;
preguntas[n]='<br>Observa el valor hexadecimal A3F59B ¿Cuántos bytes estamos indicando? ';respuestas[n]='3';n++;
preguntas[n]='¿Cuál es el primer byte de dicho valor? ';respuestas[n]='A3';n++;
preguntas[n]='¿Cuál es el segundo byte de dicho valor? ';respuestas[n]='F5';n++;
preguntas[n]='¿Cuál es el tercer byte de dicho valor? ';respuestas[n]='9B';n++;


