relacion=6; // Es la relación 1 de ejercicios de tipo Decimal-Binario

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='Habitualmente utilizamos un <b>sistema decimal</b> para representar números. ¿Qué significa esto? ';respuestas[n]='Que utilizamos diez posibles valores para cada una de las cifras';n++;
preguntas[n]='¿Cuáles son los diez posibles valores de cada cifra en el sistema decimal? ';respuestas[n]='0,1,2,3,4,5,6,7,8,9';n++;
preguntas[n]='¿Qué son los números naturales? ';respuestas[n]='Los números que sirven para contar';n++;
preguntas[n]='¿Cuál es el valor del número natural más pequeño?  ';respuestas[n]='0';n++;
preguntas[n]='Si se añaden ceros a la izquierda de un número natural ¿cambia su valor? ';respuestas[n]='No';n++;
preguntas[n]='¿Y si añadimos un cero a la derecha? (O varios) ¿Cambia el valor del número? ';respuestas[n]='Sí';n++;
preguntas[n]='¿Cuál es valor mínimo de un número de lotería de cinco cifras? (Escribe todas las cifras) ';respuestas[n]='00000';n++;
preguntas[n]='Escribe el valor anterior usando el menor número posible de cifras ';respuestas[n]='0';n++;
preguntas[n]='¿Cuál es valor máximo de un número de lotería de cinco cifras? ';respuestas[n]='99999';n++;
preguntas[n]='Para saber si un número natural es par o impar ¿Qué cifra tenemos que mirar? ';respuestas[n]='La última';n++;
preguntas[n]='Si la última cifra de un número N es 9 ¿Cuál es la última cifra de N? ';respuestas[n]='0';n++;
preguntas[n]='Si la última cifra de un número N <b>no es nueve</b> (es una cifra que llamamos A) ¿Cuál es la última cifra de N+1? ';respuestas[n]='A+1';n++;
preguntas[n]='Si un número N tiene X cifras y la última de ellas no es nueve ¿Cuántas cifras tiene N+1? ';respuestas[n]='X';n++;
preguntas[n]='Si un número N tiene X cifras y todas ellas son nueves ¿Cuántas cifras tiene N+1? ';respuestas[n]='X+1';n++;
preguntas[n]='En relación a la cuestión anterior ¿Cuál sería el valor de la primera cifra de N+1? ';respuestas[n]='1';n++;
preguntas[n]='También en relación a lo anterior ¿Cuál sería el valor todas las demás cifras de N+1? (Todas menos la primera) ';respuestas[n]='0';n++;
preguntas[n]='Escribe de forma ordenada la descomposición decimal del número 9876 ';respuestas[n]='9*1000+8*100+7*10+6*1';n++;
preguntas[n]='Escribe de forma ordenada la descomposición decimal del número 250000004 ';respuestas[n]='2*100000000+5*10000000+4*1';n++;
preguntas[n]='¿Cuánto es 10 elevado a cero? (Unidades) ';respuestas[n]='1';n++;
preguntas[n]='¿Cuánto es 10 elevado a uno? (Decenas) ';respuestas[n]='10';n++;
preguntas[n]='¿Cuánto es 10 elevado a dos? (Centenas) ';respuestas[n]='100';n++;
preguntas[n]='¿Cuánto es 10 elevado a tres? (Unidades) ';respuestas[n]='1000';n++;
preguntas[n]='Si 10 elevado a n es x ¿Cuánto es 10 elevado a n+1? ';respuestas[n]='x*10';n++;
preguntas[n]='¿Cómo es el número decimal 1 en romano? ';respuestas[n]='I';n++;
preguntas[n]='¿Cómo es el número decimal 2 en romano? ';respuestas[n]='II';n++;
preguntas[n]='¿Cómo es el número decimal 3 en romano? ';respuestas[n]='III';n++;
preguntas[n]='Si los romanos sólo hubiesen utilizado el símbolo I ¿Cómo habría sido el número decimal 4 en romano? ';respuestas[n]='IIII';n++;
preguntas[n]='¿Y el número decimal 5? ';respuestas[n]='IIIII';n++;
preguntas[n]='<br>Imagina un <b>sistema binario</b> con sólo dos dígitos, 0 y 1<br>¿Cómo sería el número decimal 0 en este sistema? ';respuestas[n]='0';n++;
preguntas[n]='¿Y el uno? ';respuestas[n]='1';n++;
preguntas[n]='Utilizando una sola cifra en dicho sistema ¿se podrían representar más números, además del cero y el uno? ';respuestas[n]='No';n++;
preguntas[n]='¿Cómo se representaría en dicho sistema el dos? ';respuestas[n]='10';n++;
preguntas[n]='¿Y el tres? ';respuestas[n]='11';n++;
preguntas[n]='Representa en binario el número siguiente al anterior ';respuestas[n]='100';n++;
preguntas[n]='Representa en binario el número siguiente al anterior ';respuestas[n]='101';n++;
preguntas[n]='Representa en binario el número siguiente al anterior ';respuestas[n]='110';n++;
preguntas[n]='Representa en binario el número siguiente al anterior ';respuestas[n]='111';n++;
preguntas[n]='Representa en binario el número siguiente al anterior ';respuestas[n]='1000';n++;
preguntas[n]='Representa en binario el número siguiente al anterior ';respuestas[n]='1001';n++;
preguntas[n]='Representa en binario el número siguiente al anterior ';respuestas[n]='1010';n++;
preguntas[n]='Representa en binario el número siguiente al anterior ';respuestas[n]='1011';n++;
preguntas[n]='Representa en binario el número siguiente al anterior ';respuestas[n]='1100';n++;
preguntas[n]='Representa en binario el número siguiente al anterior ';respuestas[n]='1101';n++;
preguntas[n]='Representa en binario el número siguiente al anterior ';respuestas[n]='1110';n++;
preguntas[n]='Representa en binario el número siguiente al anterior ';respuestas[n]='1111';n++;
preguntas[n]='¿Cuál es el valor decimal equivalente del número binario que has contestado en la respuesta anterior? ';respuestas[n]='15';n++;
preguntas[n]='¿Cuántos números distintos pueden representarse con cuatro cifras binarias? ';respuestas[n]='16';n++;
preguntas[n]='<br>Existe un sistema llamado <b>hexadecimal</b> que utiliza 16 dígitos para cada cifra. ¿Cuáles son? ';respuestas[n]='0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F';n++;
preguntas[n]='¿Cómo sería el número decimal 0 representado en hexadecimal? ';respuestas[n]='0';n++;
preguntas[n]='¿Cómo sería el número decimal 1 representado en hexadecimal? ';respuestas[n]='1';n++;
preguntas[n]='¿Cómo sería el número decimal 2 representado en hexadecimal? ';respuestas[n]='2';n++;
preguntas[n]='¿Cómo sería el número decimal 3 representado en hexadecimal? ';respuestas[n]='3';n++;
preguntas[n]='¿Cómo sería el número decimal 4 representado en hexadecimal? ';respuestas[n]='4';n++;
preguntas[n]='¿Cómo sería el número decimal 5 representado en hexadecimal? ';respuestas[n]='5';n++;
preguntas[n]='¿Cómo sería el número decimal 6 representado en hexadecimal? ';respuestas[n]='6';n++;
preguntas[n]='¿Cómo sería el número decimal 7 representado en hexadecimal? ';respuestas[n]='7';n++;
preguntas[n]='¿Cómo sería el número decimal 8 representado en hexadecimal? ';respuestas[n]='8';n++;
preguntas[n]='¿Cómo sería el número decimal 9 representado en hexadecimal? ';respuestas[n]='9';n++;
preguntas[n]='¿Cómo sería el número decimal 10 representado en hexadecimal? ';respuestas[n]='A';n++;
preguntas[n]='¿Cómo sería el número decimal 11 representado en hexadecimal? ';respuestas[n]='B';n++;
preguntas[n]='¿Cómo sería el número decimal 12 representado en hexadecimal? ';respuestas[n]='C';n++;
preguntas[n]='¿Cómo sería el número decimal 13 representado en hexadecimal? ';respuestas[n]='D';n++;
preguntas[n]='¿Cómo sería el número decimal 14 representado en hexadecimal? ';respuestas[n]='E';n++;
preguntas[n]='¿Cómo sería el número decimal 15 representado en hexadecimal? ';respuestas[n]='F';n++;
preguntas[n]='¿Cómo sería el número decimal 16 representado en hexadecimal? ';respuestas[n]='10';n++;
preguntas[n]='¿Cómo sería el número decimal 17 representado en hexadecimal? ';respuestas[n]='11';n++;
preguntas[n]='A la inversa (Cuidado): ¿Cuál sería el equivalente decimal del número hexadecimal 1F? ';respuestas[n]='31';n++;
preguntas[n]='Escribe el máximo valor hexadecimal que se puede escribir con dos cifras ';respuestas[n]='FF';n++;
preguntas[n]='¿Cuál es el valor <b>decimal</b> equivalente al número hexadecimal de la respuesta anterior? ';respuestas[n]='255';n++;
preguntas[n]='¿Cuál es el valor <b>binario</b> equivalente a este último número? ';respuestas[n]='11111111';n++;
