relacion=2; // Es la relación 2 de ejercicios de comandos Ubuntu

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='Abre la terminal y ejecuta el comando para mostrar la lista de archivos y directorios de la carpeta personal ';respuestas[n]='ls';n++;
preguntas[n]='Muestra la fecha y hora del sistema ';respuestas[n]='date';n++;
preguntas[n]='Elimina una carpeta llamada <b>hoy</b> (tal vez exista o tal vez no) ';respuestas[n]='rmdir hoy';n++;
preguntas[n]='Limpia la terminal ';respuestas[n]='clear';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>hoy</b> ';respuestas[n]='mkdir hoy';n++;
preguntas[n]='Si vuelves a ejecutar la orden anterior ¿qué sucede? ¿Por qué? (Mira la pizarra) ';respuestas[n]='Se muestra un error porque la carpeta ya existe';n++;
preguntas[n]='Cambia a la carpeta <b>hoy</b> ';respuestas[n]='cd hoy';n++;
preguntas[n]='Si vuelves a ejecutar la orden anterior ¿qué sucede? ¿Por qué? (Mira la pizarra) ';respuestas[n]='Se muestra un error porque en la carpeta actual (hoy) no existe una carpeta llamada hoy';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (hoy) ';respuestas[n]='ls';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>deportes</b> ';respuestas[n]='mkdir deportes';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>música</b> ';respuestas[n]='mkdir música';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (hoy) ';respuestas[n]='ls';n++;
preguntas[n]='¿Cuántos directorios contiene la carpeta actual en este momento? ';respuestas[n]='2';n++;
preguntas[n]='¿Cuántos archivos contiene la carpeta actual en este momento? ';respuestas[n]='0';n++;
preguntas[n]='Cambia a la carpeta <b>deportes</b> ';respuestas[n]='cd deportes';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (deportes) ';respuestas[n]='ls';n++;
preguntas[n]='Crea un archivo vacío de texto llamado <b>leeresto.txt</b> ';respuestas[n]='touch leeresto.txt';n++;
preguntas[n]='Añade una línea con el texto <b>Esta carpeta llamada deportes</b> al archivo <b>leeresto.txt</b> ';respuestas[n]='echo Esta carpeta llamada deportes>>leeresto.txt';n++;
preguntas[n]='Mostrar el contenido del archivo <b>leeresto.txt</b> ';respuestas[n]='cat leeresto.txt';n++;
preguntas[n]='Añade una línea con el texto <b>contiene varias carpetas</b> al archivo <b>leeresto.txt</b> ';respuestas[n]='echo contiene varias carpetas>>leeresto.txt';n++;
preguntas[n]='Vuelve a mostrar el contenido del archivo <b>leeresto.txt</b> ';respuestas[n]='cat leeresto.txt';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>fútbol</b> ';respuestas[n]='mkdir fútbol';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>baloncesto</b> ';respuestas[n]='mkdir baloncesto';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>tenis</b> ';respuestas[n]='mkdir tenis';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (deportes) ';respuestas[n]='ls';n++;
preguntas[n]='¿Cuántos directorios contiene la carpeta actual en este momento? ';respuestas[n]='3';n++;
preguntas[n]='¿Cuántos archivos contiene la carpeta actual en este momento? ';respuestas[n]='1';n++;
preguntas[n]='Cambia a la carpeta <b>fútbol</b> ';respuestas[n]='cd fútbol';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (fútbol) ';respuestas[n]='ls';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>española</b> ';respuestas[n]='mkdir española';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>premier</b> ';respuestas[n]='mkdir premier';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>bundesliga</b> ';respuestas[n]='mkdir bundesliga';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (fútbol) ';respuestas[n]='ls';n++;
preguntas[n]='Cambia a la carpeta superior (deportes) ';respuestas[n]='cd ..';n++;
preguntas[n]='Cambia a la carpeta <b>baloncesto</b> ';respuestas[n]='cd baloncesto';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (baloncesto) ';respuestas[n]='ls';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>acb</b> ';respuestas[n]='mkdir acb';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>nba</b> ';respuestas[n]='mkdir nba';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (baloncesto) ';respuestas[n]='ls';n++;
preguntas[n]='Cambia a la carpeta superior (deportes) ';respuestas[n]='cd ..';n++;
preguntas[n]='Cambia a la carpeta <b>tenis</b> ';respuestas[n]='cd tenis';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (tenis) ';respuestas[n]='ls';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>atp</b> ';respuestas[n]='mkdir atp';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>wta</b> ';respuestas[n]='mkdir wta';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (tenis) ';respuestas[n]='ls';n++;
preguntas[n]='Cambia a la carpeta <b>atp</b> ';respuestas[n]='cd atp';n++;
preguntas[n]='Crea un archivo vacío de texto llamado <b>jugadores.txt</b> ';respuestas[n]='touch jugadores.txt';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (atp) ';respuestas[n]='ls';n++;
preguntas[n]='Añade una línea con el texto <b>Rafael Nadal</b> al archivo <b>jugadores.txt</b> ';respuestas[n]='echo Rafael Nadal>>jugadores.txt';n++;
preguntas[n]='Mostrar el contenido del archivo <b>jugadores.txt</b> ';respuestas[n]='cat jugadores.txt';n++;
preguntas[n]='Añade una línea con el texto <b>Carlos Alcaraz</b> al archivo <b>jugadores.txt</b> ';respuestas[n]='echo Carlos Alcaraz>>jugadores.txt';n++;
preguntas[n]='Vuelve a mostrar el contenido del archivo <b>jugadores.txt</b> ';respuestas[n]='cat jugadores.txt';n++;
preguntas[n]='Añade una línea con el texto <b>Novak Djokovic</b> al archivo <b>jugadores.txt</b> ';respuestas[n]='echo Novak Djokovic>>jugadores.txt';n++;
preguntas[n]='Vuelve a mostrar el contenido del archivo <b>jugadores.txt</b> ';respuestas[n]='cat jugadores.txt';n++;
preguntas[n]='Cambia a la carpeta superior (tenis) ';respuestas[n]='cd ..';n++;
preguntas[n]='Cambia a la carpeta superior (deportes) ';respuestas[n]='cd ..';n++;
preguntas[n]='Cambia a la carpeta superior (hoy) ';respuestas[n]='cd ..';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (hoy) ';respuestas[n]='ls';n++;
preguntas[n]='Cambia a la carpeta <b>música</b> ';respuestas[n]='cd música';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>clásica</b> ';respuestas[n]='mkdir clásica';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>moderna</b> ';respuestas[n]='mkdir moderna';n++;
preguntas[n]='Crea una nueva carpeta llamada <b>maldita</b> ';respuestas[n]='mkdir maldita';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (música) ';respuestas[n]='ls';n++;
preguntas[n]='Cambia a la carpeta <b>clásica</b> ';respuestas[n]='cd clásica';n++;
preguntas[n]='Crea un archivo vacío de texto llamado <b>músicos.txt</b> ';respuestas[n]='touch músicos.txt';n++;
preguntas[n]='Muestra el contenido de la carpeta actual (clásica) ';respuestas[n]='ls';n++;
preguntas[n]='Añade una línea con el texto <b>Beethoven</b> al archivo <b>músicos.txt</b> ';respuestas[n]='echo Beethoven>>músicos.txt';n++;
preguntas[n]='Añade una línea con el texto <b>Mozart</b> al archivo <b>músicos.txt</b> ';respuestas[n]='echo Mozart>>músicos.txt';n++;
preguntas[n]='Añade una línea con el texto <b>Bach</b> al archivo <b>músicos.txt</b> ';respuestas[n]='echo Bach>>músicos.txt';n++;
preguntas[n]='Añade una línea con el texto <b>Wagner</b> al archivo <b>músicos.txt</b> ';respuestas[n]='echo Wagner>>músicos.txt';n++;
preguntas[n]='Mostrar el contenido del archivo <b>músicos.txt</b> ';respuestas[n]='cat músicos.txt';n++;
preguntas[n]='Crea un archivo vacío de texto llamado <b>estilos.txt</b> ';respuestas[n]='touch estilos.txt';n++;
preguntas[n]='Volver a mostrar el contenido de la carpeta actual (clásica) ';respuestas[n]='ls';n++;
preguntas[n]='Añade una línea con el texto <b>Ópera</b> al archivo <b>estilos.txt</b> ';respuestas[n]='echo Ópera>>estilos.txt';n++;
preguntas[n]='Añade una línea con el texto <b>Sinfónica</b> al archivo <b>estilos.txt</b> ';respuestas[n]='echo Sinfónica>>estilos.txt';n++;
preguntas[n]='Añade una línea con el texto <b>Música de cámara</b> al archivo <b>estilos.txt</b> ';respuestas[n]='echo Música de cámara>>estilos.txt';n++;
preguntas[n]='Mostrar el contenido del archivo <b>estilos.txt</b> ';respuestas[n]='cat estilos.txt';n++;
preguntas[n]='Cambiar el nombre del archivo <b>estilos.txt</b> por el nuevo nombre <b>géneros.txt</b> ';respuestas[n]='mv estilos.txt géneros.txt';n++;
preguntas[n]='Mostrar el contenido del archivo <b>géneros.txt</b> ';respuestas[n]='cat géneros.txt';n++;
preguntas[n]='Hacer una copia del archivo <b>géneros.txt</b> y llamarla <b>copia.txt</b> ';respuestas[n]='cp géneros.txt copia.txt';n++;
preguntas[n]='Volver a mostrar el contenido de la carpeta actual (clásica) ';respuestas[n]='ls';n++;
preguntas[n]='Mostrar el contenido del archivo <b>copia.txt</b> ';respuestas[n]='cat copia.txt';n++;
preguntas[n]='Eliminar el archivo <b>copia.txt</b> ';respuestas[n]='rm copia.txt';n++;
preguntas[n]='Volver a mostrar el contenido de la carpeta actual (clásica) ';respuestas[n]='ls';n++;
preguntas[n]='Ejecuta el comando para mostrar la ruta actual ';respuestas[n]='pwd';n++;
preguntas[n]='Cambia a la carpeta superior (música) ';respuestas[n]='cd ..';n++;
preguntas[n]='Intenta eliminar la carpeta <b>clásica</b> y verás que no se puede (no está vacía) ';respuestas[n]='rmdir clásica';n++;
preguntas[n]='Elimina la carpeta <b>maldita</b> (esta carpeta sí está vacía, sí se puede) ';respuestas[n]='rmdir maldita';n++;
preguntas[n]='Si vuelves a ejecutar la orden anterior ¿qué sucede? (Piensa por qué) ';respuestas[n]='Se muestra un error porque la carpeta maldita ya no existe';n++;
preguntas[n]='Cambia a la carpeta superior (hoy) ';respuestas[n]='cd ..';n++;
preguntas[n]='Mostrar el contenido de la carpeta actual (hoy) ';respuestas[n]='ls';n++;
preguntas[n]='Cambia a la carpeta superior (Carpeta personal) ';respuestas[n]='cd ..';n++;
preguntas[n]='Mostrar el contenido de la carpeta actual (Carpeta personal) ';respuestas[n]='ls';n++;
preguntas[n]='Intenta eliminar la carpeta <b>hoy</b> y verás que no se puede (no está vacía) ';respuestas[n]='rmdir hoy';n++;
preguntas[n]='Ejecuta el comando para apagar el equipo dentro de un minuto ';respuestas[n]='shutdown';n++;
preguntas[n]='¡Rapido! Cancela la acción anterior para que el equipo no se apague ';respuestas[n]='shutdown -c';n++;
preguntas[n]='Limpia la terminal ';respuestas[n]='clear';n++;
preguntas[n]='Ejecuta el comando para mostrar el manual de ayuda de la orden que has ejecutado en el ejercicio anterior ';respuestas[n]='man clear';n++;
preguntas[n]='Ejecuta el comando para salir de la terminal ';respuestas[n]='exit';n++;
preguntas[n]='Accede a la carpeta personal y elimina la carpeta <b>hoy</b><br>En modo gráfico ¿se puede hacer, aunque no esté vacía? ';respuestas[n]='Sí';n++;
