relacion=2; // Para mostrar al principio de la página: Relación nº...

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='1 ';respuestas[n]='placa madre o motherboard';n++;
preguntas[n]='2 ';respuestas[n]='circuito impreso';n++;
preguntas[n]='3 ';respuestas[n]='procesador o CPU';n++;
preguntas[n]='4 ';respuestas[n]='memoria RAM';n++;
preguntas[n]='5 ';respuestas[n]='puertos';n++;
preguntas[n]='6 ';respuestas[n]='socket';n++;
preguntas[n]='7 ';respuestas[n]='CPU';n++;
preguntas[n]='8 ';respuestas[n]='LGA';n++;
preguntas[n]='9 ';respuestas[n]='AM4 / AM5';n++;
preguntas[n]='10 ';respuestas[n]='Northbridge';n++;
preguntas[n]='11 ';respuestas[n]='Southbridge';n++;
preguntas[n]='12 ';respuestas[n]='PCH (Platform Controller Hub)';n++;
preguntas[n]='13 ';respuestas[n]='DIMM';n++;
preguntas[n]='14 ';respuestas[n]='DDR4 / DDR5';n++;
preguntas[n]='15 ';respuestas[n]='capacidad máxima soportada';n++;
preguntas[n]='16 ';respuestas[n]='ranuras de expansión';n++;
preguntas[n]='17 ';respuestas[n]='PCI Express / PCIe';n++;
preguntas[n]='18 ';respuestas[n]='PCI';n++;
preguntas[n]='19 ';respuestas[n]='PCIe x1';n++;
preguntas[n]='20 ';respuestas[n]='PCIe x4';n++;
preguntas[n]='21 ';respuestas[n]='PCIe x16';n++;
preguntas[n]='22 ';respuestas[n]='SATA';n++;
preguntas[n]='23 ';respuestas[n]='M.2';n++;
preguntas[n]='24 ';respuestas[n]='24';n++;
preguntas[n]='25 ';respuestas[n]='4';n++;
preguntas[n]='26 ';respuestas[n]='8';n++;
preguntas[n]='27 ';respuestas[n]='BIOS';n++;
preguntas[n]='28 ';respuestas[n]='UEFI';n++;
preguntas[n]='29 ';respuestas[n]='batería CMOS';n++;
preguntas[n]='30 ';respuestas[n]='SYS_FAN / CHA_FAN';n++;
preguntas[n]='31 ';respuestas[n]='USB';n++;
preguntas[n]='32 ';respuestas[n]='HD Audio';n++;
preguntas[n]='33 ';respuestas[n]='tarjeta gráfica';n++;
preguntas[n]='34 ';respuestas[n]='tarjeta de sonido';n++;
preguntas[n]='35 ';respuestas[n]='tarjeta de red';n++;
preguntas[n]='36 ';respuestas[n]='M.2 NVMe';n++;
preguntas[n]='37 ';respuestas[n]='controles RGB / ARGB';n++;
preguntas[n]='38 ';respuestas[n]='cables SATA';n++;
preguntas[n]='39 ';respuestas[n]='panel frontal / front panel';n++;
preguntas[n]='40 ';respuestas[n]='FAN';n++;
preguntas[n]='41 ';respuestas[n]='cables SATA (para unidades ópticas modernas)';n++;
preguntas[n]='42 ';respuestas[n]='ATX';n++;
preguntas[n]='43 ';respuestas[n]='micro-ATX';n++;
preguntas[n]='44 ';respuestas[n]='mini-ITX';n++;
preguntas[n]='45 ';respuestas[n]='E-ATX';n++;
preguntas[n]='46 ';respuestas[n]='ASUS';n++;
preguntas[n]='47 ';respuestas[n]='MSI';n++;
preguntas[n]='48 ';respuestas[n]='Gigabyte';n++;
preguntas[n]='49 ';respuestas[n]='ASRock';n++;
preguntas[n]='50 ';respuestas[n]='ROG (Republic of Gamers)';n++;
preguntas[n]='51 ';respuestas[n]='MPG / MAG';n++;
preguntas[n]='52 ';respuestas[n]='AORUS';n++;
preguntas[n]='53 ';respuestas[n]='Phantom Gaming';n++;
preguntas[n]='54 ';respuestas[n]='ordenador';n++;
