relacion=3; // Para mostrar al principio de la página: Relación nº...

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='¿Cómo se llama la placa base principal del ordenador? (En español) ';respuestas[n]='placa madre';n++;
preguntas[n]='¿Cómo se llama la placa base principal del ordenador? (En inglés) ';respuestas[n]='motherboard';n++;
preguntas[n]='¿Qué importante componente ejecuta las instrucciones del sistema? ';respuestas[n]='procesador';n++;
preguntas[n]='¿Qué siglas en inglés se utilizan para nombrar el procesador? ';respuestas[n]='CPU';n++;
preguntas[n]='¿Qué parte del procesador se encarga de realizar operaciones? (Siglas en inglés) ';respuestas[n]='ALU';n++;
preguntas[n]='¿Qué parte del procesador se encarga de encargada de interpretar y coordinar la ejecución de instrucciones? ';respuestas[n]='unidad de control';n++;
preguntas[n]='¿Qué componente almacena datos de forma permanente? (El más frecuente en PCs y de mayor capacidad) ';respuestas[n]='disco duro';n++;
preguntas[n]='¿Qué componente se encarga de los gráficos? ';respuestas[n]='tarjeta gráfica';n++;
preguntas[n]='¿Qué componente se utiliza para refrigerar la CPU? ';respuestas[n]='disipador';n++;
preguntas[n]='¿Qué componente proporciona energía al ordenador? ';respuestas[n]='fuente de alimentación';n++;
preguntas[n]='¿Qué componente permite introducir texto? ';respuestas[n]='teclado';n++;
preguntas[n]='¿Qué componente permite mostrar la información en pantalla? ';respuestas[n]='monitor';n++;
preguntas[n]='¿Cómo se llama el lugar donde se instala la CPU en la placa? (En español) ';respuestas[n]='zócalo';n++;
preguntas[n]='¿Cómo se llama el lugar donde se instala la CPU en la placa? (En ingés) ';respuestas[n]='socket';n++;
preguntas[n]='¿Cómo se llama el firmware clásico de arranque del PC? ';respuestas[n]='BIOS';n++;
preguntas[n]='¿Cómo se llama su versión moderna? ';respuestas[n]='UEFI';n++;
preguntas[n]='¿Qué tecla se usa habitualmente para entrar en la BIOS cuando el sistema está arrancando? ';respuestas[n]='F2';n++;
preguntas[n]='Dependiendo del fabricante ¿puede ser una tecla distinta de la anterior? ';respuestas[n]='sí';n++;
preguntas[n]='¿Qué pieza mantiene la configuración de la BIOS sin corriente? ';respuestas[n]='batería CMOS';n++;
preguntas[n]='¿Cómo se llaman los contactos metálicos del procesador? ';respuestas[n]='pines';n++;
preguntas[n]='¿Cuántos pines tiene normalmente el conector principal de la placa base? ';respuestas[n]='24';n++;
preguntas[n]='¿Cómo se llaman las líneas de conexión de la placa base? (plural) ';respuestas[n]='buses';n++;
preguntas[n]='¿Qué componente coordina la comunicación entre dispositivos en placas modernas? ';respuestas[n]='PCH';n++;
preguntas[n]='¿Qué componente almacena datos de forma temporal? (Siglas en inglés) ';respuestas[n]='RAM';n++;
preguntas[n]='¿Qué tipo de ranura utiliza la RAM en ordenadores actuales? ';respuestas[n]='DIMM';n++;
preguntas[n]='¿Cuántos bits tiene un sistema operativo actual? ';respuestas[n]='64';n++;
preguntas[n]='¿Qué interfaz se usa para discos duros tradicionales? ';respuestas[n]='SATA';n++;
preguntas[n]='¿Qué tipo de disco duro almacena información de forma mecánica en platos giratorios? ';respuestas[n]='HDD';n++;
preguntas[n]='¿Qué tipo de disco duro almacena información de forma electrónica sin partes móviles? ';respuestas[n]='SSD';n++;
preguntas[n]='¿Cómo se llama el formato de SSD que va directamente a la placa? ';respuestas[n]='M.2';n++;
preguntas[n]='¿Qué tipo de SSD es más rápido, SATA o NVME? ';respuestas[n]='NVME';n++;
preguntas[n]='¿Qué puerto se usa para conectar teclado y ratón antiguos? ';respuestas[n]='PS/2';n++;
preguntas[n]='¿Qué puerto se usa para conectar monitores antiguos? ';respuestas[n]='VGA';n++;
preguntas[n]='¿Qué puerto, usado para monitores modernos, transmite audio y vídeo digital? ';respuestas[n]='HDMI';n++;
preguntas[n]='¿Qué puerto se usa para conectar impresoras antiguas? ';respuestas[n]='LPT';n++;
preguntas[n]='¿Qué puerto es de tipo rectangular y muy común hoy en día? ';respuestas[n]='USB';n++;
preguntas[n]='¿Qué tipo de conector se usa para ventiladores? ';respuestas[n]='FAN';n++;
preguntas[n]='¿Qué conector se usa para discos SATA? ';respuestas[n]='SATA';n++;
preguntas[n]='¿Qué conector se usa para USB frontales? ';respuestas[n]='USB';n++;
preguntas[n]='¿Qué formato de placa es el más común en PCs de sobremesa? ';respuestas[n]='ATX';n++;
preguntas[n]='¿Qué formato es más pequeño, ATX o micro-ATX? ';respuestas[n]='micro-ATX';n++;
preguntas[n]='¿Qué formato es el más pequeño de todos? ';respuestas[n]='mini-ITX';n++;
preguntas[n]='¿Qué formato es más grande que ATX? ';respuestas[n]='E-ATX';n++;
preguntas[n]='¿Cuántas ranuras PCIe x16 suele tener una placa básica? ';respuestas[n]='1';n++;
preguntas[n]='¿Qué herramienta se usa principalmente para montar un PC? ';respuestas[n]='destornillador';n++;
preguntas[n]='¿Qué elementos se usan para fijar la placa a la caja? ';respuestas[n]='tornillos';n++;
preguntas[n]='¿Qué elemento evita descargas eléctricas al tocar componentes? ';respuestas[n]='pulsera antiestática';n++;
preguntas[n]='¿Qué sustancia se utiliza para crear una capa entre el procesador y el disipador de calor? ';respuestas[n]='pasta térmica';n++;
preguntas[n]='¿Qué acción se realiza para eliminar polvo del interior del PC? ';respuestas[n]='limpieza';n++;
preguntas[n]='¿Cada cuántos meses es recomendable limpiar un PC? ';respuestas[n]='6';n++;
preguntas[n]='¿Qué es lo primero que se debe desconectar antes de cambiar un componente? ';respuestas[n]='corriente eléctrica';n++;
preguntas[n]='¿Qué componente se limpia con mayor frecuencia? ';respuestas[n]='ventilador';n++;
preguntas[n]='¿Qué producto se usa para limpiar contactos electrónicos? ';respuestas[n]='alcohol';n++;
preguntas[n]='¿Qué conector sirve para altavoces traseros de un PC? ';respuestas[n]='audio';n++;
preguntas[n]='¿Qué puerto permite conectar red por cable? (Ethernet) ';respuestas[n]='RJ45';n++;
preguntas[n]='¿Qué puerto se usa para tarjetas de expansión antiguas? ';respuestas[n]='PCI';n++;
preguntas[n]='¿Qué ranura de expansión permite tarjetas modernas? (Última letra en minúscula) ';respuestas[n]='PCIe';n++;
preguntas[n]='¿Qué componente convierte la corriente alterna en continua? ';respuestas[n]='fuente de alimentación';n++;
preguntas[n]='¿Qué tipo de memoria no volátil almacena BIOS/UEFI? ';respuestas[n]='flash';n++;
preguntas[n]='¿Qué tipo de disipador es más silencioso, ventilador o líquido? ';respuestas[n]='líquido';n++;
preguntas[n]='¿Qué puerto permite conectar un ratón o teclado moderno, además de otros dispositivos? ';respuestas[n]='USB';n++;
preguntas[n]='¿Qué conector sirve para ventilación del CPU? ';respuestas[n]='CPU_FAN';n++;
preguntas[n]='¿Qué tipo de chip controla el sonido en la placa? ';respuestas[n]='tarjeta de sonido';n++;
preguntas[n]='¿Qué tipo de chip controla la red cableada? ';respuestas[n]='tarjeta de red';n++;
preguntas[n]='¿Qué tipo de memoria gráfica se encuentra en la tarjeta de vídeo? ';respuestas[n]='GDDR';n++;
preguntas[n]='¿Qué formato de RAM se usa en portátiles? ';respuestas[n]='SO-DIMM';n++;
preguntas[n]='¿Qué conector alimenta ventiladores de caja? ';respuestas[n]='FAN';n++;
preguntas[n]='¿Qué puerto se usa para dispositivos de audio digital? ';respuestas[n]='SPDIF';n++;
preguntas[n]='¿Qué puerto permite carga rápida y transferencia de datos? ';respuestas[n]='USB-C';n++;
preguntas[n]='¿Qué tipo de conector se usa para la unidad óptica? ';respuestas[n]='SATA';n++;
preguntas[n]='¿Qué puerto antiguo se usaba para módems? ';respuestas[n]='COM';n++;
preguntas[n]='¿Qué tipo de memoria es más rápida, RAM o disco? ';respuestas[n]='RAM';n++;
preguntas[n]='¿Qué tipo de tarjeta se instala en PCIe x16? ';respuestas[n]='gráfica';n++;
preguntas[n]='¿Qué chip gestiona la comunicación entre CPU y periféricos? ';respuestas[n]='PCH';n++;
