descripcion="PROGRAMACIÓN BÁSICA EN JAVASCRIPT - EJERCICIOS Y CUESTIONES - RELACIÓN Nº 4";

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]=alert("Bienvenido");;respuestas[n]='Mostrar un mensaje "Bienvenido" en una ventana emergente';n++;	
//preguntas[n]=alert("Bienvenid@\na la clase de JavaScript");;respuestas[n]='Mostrar un mensaje en varias líneas: "Bienvenid@" y "a la clase de JavaScript"';n++;	
preguntas[n]=edad=prompt("¿Cuál es tu edad?");;respuestas[n]='Preguntar al usuario su edad y guardarla en una variable llamada edad';n++;	
preguntas[n]=alert("Tienes "+edad+" años");;respuestas[n]='Mostrar un mensaje diciendo "Tienes X años", usando la variable edad';n++;	
preguntas[n]=longitudEdad=edad.length;;respuestas[n]='Guardar en una variable longitudEdad la longitud de la cadena que representa la edad';n++;	
preguntas[n]=primerDigito=edad[0];;respuestas[n]='Guardar el primer dígito de la edad en una variable llamada primerDigito';n++;	
preguntas[n]=edadNum=parseInt(edad);;respuestas[n]='Convertir la edad a número entero y guardarla en una variable llamada edadNum';n++;	
preguntas[n]=ciudad=prompt("¿En qué ciudad vives?");;respuestas[n]='Preguntar al usuario su ciudad y guardar la respuesta en una variable llamada ciudad';n++;	
preguntas[n]=ciudad=ciudad.toUpperCase();;respuestas[n]='Convertir el nombre de la ciudad a mayúsculas';n++;	
preguntas[n]=ciudad=ciudad.toLowerCase();;respuestas[n]='Convertir el nombre de la ciudad a minúsculas';n++;	
preguntas[n]=ciudad=ciudad.trim();;respuestas[n]='Eliminar espacios al inicio y al final de la variable ciudad';n++;	
preguntas[n]=mensaje="Hola, "+edad+", "+ciudad;;respuestas[n]='Crear una variable mensaje que combine "Hola", el nombre y la ciudad, separadas por comas y dejando un espacio después de cada coma';n++;	
preguntas[n]=alert(mensaje);;respuestas[n]='Mostrar el mensaje anterior en una ventana emergente';n++;	
preguntas[n]=num1=1*prompt("Dime un número");;respuestas[n]='Preguntar al usuario un número y guardarlo en una variable llamada num1';n++;	
preguntas[n]=num2=1*prompt("Dime otro número");;respuestas[n]='Preguntar al usuario otro número y guardarlo en una variable llamada num2';n++;	
preguntas[n]=suma=num1+num2;;respuestas[n]='Calcular la suma de num1 y num2 y guardarla en una variable suma';n++;	
preguntas[n]=alert("El resultado de la suma es "+suma);;respuestas[n]='Mostrar la suma con un mensaje: "El resultado de la suma es "';n++;	
preguntas[n]=resta=num1-num2;producto=num1*num2;division=num1/num2;;respuestas[n]='Calcular la resta, multiplicación y división exacta de num1 y num2, guardando cada resultado en respectivamente en las variables resta, producto y division (sin tilde)';n++;	
preguntas[n]=cociente=parseInt(num1/num2);;respuestas[n]='Calcular la división entera de num1 entre num2 y guardarla en una variable llamada cociente';n++;	
preguntas[n]=resto=num1%num2;;respuestas[n]='Calcular el resto de dividir num1 entre num2 y guardarlo en una variable llamada resto';n++;	
preguntas[n]=potencia=num1**num2;;respuestas[n]='Elevar num1 a la potencia num2 y guardarlo en una variable llamada potencia';n++;	
preguntas[n]=rand=Math.random();;respuestas[n]='Generar un número aleatorio entre 0 y 1 y guardarlo en una variable llamada rand';n++;	
preguntas[n]=rand=50*Math.random()+1;;respuestas[n]='Generar un número aleatorio entre 1 y 50 (con decimales) y guardarlo en rand';n++;	
preguntas[n]=rand=1+parseInt(50*Math.random());;respuestas[n]='Generar un número entero aleatorio entre 1 y 50 y guardarlo en rand';n++;	
preguntas[n]=moneda=parseInt(2*Math.random());;respuestas[n]='Generar un número entero aleatorio entre 1 y 50 y guardarlo en una variable llamada moneda';n++;	
preguntas[n]=if(moneda==0) alert("cara");else alert("cruz");;respuestas[n]='Mostrar "cara" o "cruz" dependiendo del valor obtenido en la sentencia anterior';n++;	
preguntas[n]=notaExamen=1*prompt("Dime tu nota de examen");;respuestas[n]='Preguntar al usuario su nota de un examen y guardarla en una variable llamada notaExamen';n++;	
preguntas[n]=if(notaExamen>=5) alert("Aprobado");else alert("Suspenso");;respuestas[n]='Mostrar "Aprobado" si la nota es mayor o igual a 6, "Suspenso" en caso contrario';n++;	
preguntas[n]=bebida=prompt("¿Cuál es tu bebida favorita?");;respuestas[n]='Preguntar al usuario su bebida favorita y guardarla en una variable llamada bebida';n++;	
preguntas[n]=alert("Tu bebida favorita es "+bebida);;respuestas[n]='Mostrar un mensaje que diga "Tu bebida favorita es X", usando la variable bebida de la línea anterior';n++;	
preguntas[n]=palabra1=prompt("Dime una palabra");;respuestas[n]='Preguntar al usuario una palabra (variable palabra1)';n++;	
preguntas[n]=palabra2=prompt("Dime otra palabra");;respuestas[n]='Preguntar al usuario otra palabra (variable palabra2)';n++;	
preguntas[n]=combinada=palabra1+"-"+palabra2;;respuestas[n]='Crear una nueva variable llamada combinada que encadene las dos palabras anteriores separadas por un guion';n++;	

