descripcion="PROGRAMACIÓN BÁSICA EN JAVASCRIPT - EJERCICIOS Y CUESTIONES - RELACIÓN Nº 4";

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='Mostrar un mensaje "Bienvenido" en una ventana emergente ';respuestas[n]='alert("Bienvenido");';n++;
preguntas[n]='Mostrar un mensaje en varias líneas: "Bienvenid@" y "a la clase de JavaScript" ';respuestas[n]='alert("Bienvenid@\na la clase de JavaScript");';n++;
preguntas[n]='Preguntar al usuario su edad y guardarla en una variable llamada edad ';respuestas[n]='edad=prompt("¿Cuál es tu edad?");';n++;
preguntas[n]='Mostrar un mensaje diciendo "Tienes X años", usando la variable edad ';respuestas[n]='alert("Tienes "+edad+" años");';n++;
preguntas[n]='Guardar en una variable longitudEdad la longitud de la cadena que representa la edad ';respuestas[n]='longitudEdad=edad.length;';n++;
preguntas[n]='Guardar el primer dígito de la edad en una variable llamada primerDigito ';respuestas[n]='primerDigito=edad[0];';n++;
preguntas[n]='Convertir la edad a número entero y guardarla en una variable llamada edadNum ';respuestas[n]='edadNum=parseInt(edad);';n++;
preguntas[n]='Preguntar al usuario su ciudad y guardar la respuesta en una variable llamada ciudad ';respuestas[n]='ciudad=prompt("¿En qué ciudad vives?");';n++;
preguntas[n]='Convertir el nombre de la ciudad a mayúsculas ';respuestas[n]='ciudad=ciudad.toUpperCase();';n++;
preguntas[n]='Convertir el nombre de la ciudad a minúsculas ';respuestas[n]='ciudad=ciudad.toLowerCase();';n++;
preguntas[n]='Eliminar espacios al inicio y al final de la variable ciudad ';respuestas[n]='ciudad=ciudad.trim();';n++;
preguntas[n]='Crear una variable mensaje que combine "Hola", el nombre y la ciudad, separadas por comas y dejando un espacio después de cada coma ';respuestas[n]='mensaje="Hola, "+edad+", "+ciudad;';n++;
preguntas[n]='Mostrar el mensaje anterior en una ventana emergente ';respuestas[n]='alert(mensaje);';n++;
preguntas[n]='Preguntar al usuario un número y guardarlo en una variable llamada num1 ';respuestas[n]='num1=1*prompt("Dime un número");';n++;
preguntas[n]='Preguntar al usuario otro número y guardarlo en una variable llamada num2 ';respuestas[n]='num2=1*prompt("Dime otro número");';n++;
preguntas[n]='Calcular la suma de num1 y num2 y guardarla en una variable suma ';respuestas[n]='suma=num1+num2;';n++;
preguntas[n]='Mostrar la suma con un mensaje: "El resultado de la suma es " ';respuestas[n]='alert("El resultado de la suma es "+suma);';n++;
preguntas[n]='Calcular la resta, multiplicación y división exacta de num1 y num2, guardando cada resultado en respectivamente en las variables resta, producto y division (sin tilde) ';respuestas[n]='resta=num1-num2;producto=num1*num2;division=num1/num2;';n++;
preguntas[n]='Calcular la división entera de num1 entre num2 y guardarla en una variable llamada cociente ';respuestas[n]='cociente=parseInt(num1/num2);';n++;
preguntas[n]='Calcular el resto de dividir num1 entre num2 y guardarlo en una variable llamada resto ';respuestas[n]='resto=num1%num2;';n++;
preguntas[n]='Elevar num1 a la potencia num2 y guardarlo en una variable llamada potencia ';respuestas[n]='potencia=num1**num2;';n++;
preguntas[n]='Generar un número aleatorio entre 0 y 1 y guardarlo en una variable llamada rand ';respuestas[n]='rand=Math.random();';n++;
preguntas[n]='Generar un número aleatorio entre 1 y 50 (con decimales) y guardarlo en rand ';respuestas[n]='rand=50*Math.random()+1;';n++;
preguntas[n]='Generar un número entero aleatorio entre 1 y 50 y guardarlo en rand ';respuestas[n]='rand=1+parseInt(50*Math.random());';n++;
preguntas[n]='Generar un número entero aleatorio entre 1 y 50 y guardarlo en una variable llamada moneda ';respuestas[n]='moneda=parseInt(2*Math.random());';n++;
preguntas[n]='Mostrar "cara" o "cruz" dependiendo del valor obtenido en la sentencia anterior ';respuestas[n]='if(moneda==0) alert("cara");else alert("cruz");';n++;
preguntas[n]='Preguntar al usuario su nota de un examen y guardarla en una variable llamada notaExamen ';respuestas[n]='notaExamen=1*prompt("Dime tu nota de examen");';n++;
preguntas[n]='Mostrar "Aprobado" si la nota es mayor o igual a 6, "Suspenso" en caso contrario ';respuestas[n]='if(notaExamen>=5) alert("Aprobado");else alert("Suspenso");';n++;
preguntas[n]='Preguntar al usuario su bebida favorita y guardarla en una variable llamada bebida ';respuestas[n]='bebida=prompt("¿Cuál es tu bebida favorita?");';n++;
preguntas[n]='Mostrar un mensaje que diga "Tu bebida favorita es X", usando la variable bebida de la línea anterior ';respuestas[n]='alert("Tu bebida favorita es "+bebida);';n++;
preguntas[n]='Preguntar al usuario una palabra (variable palabra1) ';respuestas[n]='palabra1=prompt("Dime una palabra");';n++;
preguntas[n]='Preguntar al usuario otra palabra (variable palabra2) ';respuestas[n]='palabra2=prompt("Dime otra palabra");';n++;
preguntas[n]='Crear una nueva variable llamada combinada que encadene las dos palabras anteriores separadas por un guion ';respuestas[n]='combinada=palabra1+"-"+palabra2;';n++;
