descripcion="PROGRAMACIÓN BÁSICA EN JAVASCRIPT - EJERCICIOS Y CUESTIONES - RELACIÓN Nº 3";

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='Mostrar un mensaje "Hola" en una ventana emergente ';respuestas[n]='alert("Hola")';n++;	
preguntas[n]='Mostrar un mensaje en varias líneas: "Hola" y "¿Qué tal?" ';respuestas[n]='alert("Hola\n¿Qué tal?")';n++;	
preguntas[n]='Preguntar al usuario ¿Cómo te llamas? y guardar la respuesta en una variable llamada nombre ';respuestas[n]='nombre=prompt("¿Cómo te llamas?")';n++;	
preguntas[n]='Mostrar un saludo usando el nombre del usuario ';respuestas[n]='alert("Hola "+nombre)';n++;	
preguntas[n]='Obtener la longitud de la cadena nombre y guardarla en una variable llamada n ';respuestas[n]='n=nombre.length';n++;	
preguntas[n]='Guardar el primer carácter de nombre en una variable llamada caracter ';respuestas[n]='caracter=nombre[0]';n++;	
preguntas[n]='Guardar el segundo carácter de nombre en caracter ';respuestas[n]='caracter=nombre[1]';n++;	
preguntas[n]='Guardar el tercer carácter de nombre en caracter ';respuestas[n]='caracter=nombre[2]';n++;	
preguntas[n]='Guardar el último carácter de nombre en caracter ';respuestas[n]='caracter=nombre[n-1]';n++;	
preguntas[n]='Eliminar espacios al inicio y al final de nombre ';respuestas[n]='nombre=nombre.trim()';n++;	
preguntas[n]='Convertir nombre a mayúsculas ';respuestas[n]='nombre=nombre.toUpperCase()';n++;	
preguntas[n]='Convertir nombre a minúsculas ';respuestas[n]='nombre=nombre.toLowerCase()';n++;	
preguntas[n]='Preguntar "Dime tu apellido" y guardarlo en una variable llamada apellido ';respuestas[n]='apellido=prompt("Dime tu apellido")';n++;	
preguntas[n]='Crear una cadena completa con nombre y apellido y guardarla en una variable llamada completo ';respuestas[n]='completo=nombre+" "+apellido';n++;	
preguntas[n]='Mostrar el nombre completo ';respuestas[n]='alert(completo)';n++;	
preguntas[n]='Preguntar "Dime un número" y convertirlo a tipo numérico usando multiplicación por 1, guardarlo en una variable llamada a ';respuestas[n]='a=1*prompt("Dime un número")';n++;	
preguntas[n]='Preguntar "Dime otro número" y convertirlo a tipo numérico, guardarlo en una variable llamada b ';respuestas[n]='b=1*prompt("Dime otro número")';n++;	
preguntas[n]='Sumar a y b, guardar en en una variable llamada c ';respuestas[n]='c=a+b';n++;	
preguntas[n]='Mostrar el resultado de la suma anterior ';respuestas[n]='alert(c)';n++;	
preguntas[n]='Mostrar la suma con mensaje "La suma es" (deja un espacio) ';respuestas[n]='alert("La suma es "+c)';n++;	
preguntas[n]='Restar a menos b, guardar en c ';respuestas[n]='c=a-b';n++;	
preguntas[n]='Multiplicar a por b, guardar en c ';respuestas[n]='c=a*b';n++;	
preguntas[n]='Dividir a entre b, guardar en c ';respuestas[n]='c=a/b';n++;	
preguntas[n]='Dividir a entre b y convertir a entero, guardar en c ';respuestas[n]='c=parseInt(a/b)';n++;	
preguntas[n]='Obtener el resto de dividir a entre b, guardar en c ';respuestas[n]='c=a%b';n++;	
preguntas[n]='Elevar a a la potencia b, guardar en c ';respuestas[n]='c=a**b';n++;	
preguntas[n]='Obtener un número aleatorio entre 0 y 1 y guardarlo en una variable llamada x ';respuestas[n]='x=Math.random()';n++;	
preguntas[n]='Obtener un número aleatorio entre 0 y 100 y guardarlo en x (resultado con decimales) ';respuestas[n]='x=100*Math.random()';n++;	
preguntas[n]='Obtener un número ENTERO aleatorio entre 0 y 100 y guardarlo en x ';respuestas[n]='x=parseInt(100*Math.random())';n++;	
preguntas[n]='Simular un lanzamiento de dado y guardar en x ';respuestas[n]='x=1+parseInt(6*Math.random())';n++;	
preguntas[n]='Preguntar al usuario "Dime tu nota en el examen", convertir a número y guardar en una variable llamada nota ';respuestas[n]='nota=1*prompt("Dime tu nota en el examen")';n++;	
preguntas[n]='Mostrar "Aprobado/a" si nota es mayor o igual a 5 ';respuestas[n]='if(nota>=5) alert("Aprobado/a")';n++;	
preguntas[n]='Continuando con lo anterior, en caso contrario mostrar "Suspenso/a" ';respuestas[n]='else alert("Suspenso/a")';n++;	
preguntas[n]='¿Qué hay que escribir delante de un texto para convertirlo en comentario? ';respuestas[n]='//';n++;	
preguntas[n]='¿Qué hay que escribir encima de un conjunto de líneas para convertir todas ellas en comentario? ';respuestas[n]='/*';n++;	
preguntas[n]='¿Qué hay que escribir por debajo de la última línea del bloque de comentario? ';respuestas[n]='*/';n++;	

