descripcion="COMANDOS WINDOWS - EJERCICIOS Y CUESTIONES - RELACIÓN Nº 1";
// Es la relación 1 de comandos Windows

preguntas=new Array();
respuestas=new Array();
n=0;

preguntas[n]='Comando para acceder a la consola de Windows (desde fuera) ';respuestas[n]='cmd';n++;
preguntas[n]='Una vez dentro de la consola, ejecuta el comando anterior. ¿A qué otro comado se parece? ';respuestas[n]='ver';n++;
preguntas[n]='Atajo para maximizar / restaurar el tamaño de la consola abierta (no es maximizar la ventana) ';respuestas[n]='Alt + Intro';n++;
preguntas[n]='Limpiar la pantalla ';respuestas[n]='cls';n++;
preguntas[n]='Salir de la consola ';respuestas[n]='exit';n++;
preguntas[n]='Mostrar la fecha ';respuestas[n]='date';n++;
preguntas[n]='Mostrar la fecha sin pedir cambio ';respuestas[n]='date /t';n++;
preguntas[n]='Mostrar la hora ';respuestas[n]='time';n++;
preguntas[n]='Mostrar la hora sin pedir cambio ';respuestas[n]='time /t';n++;
preguntas[n]='Mostrar la ruta del directorio actual ';respuestas[n]='cd';n++;
preguntas[n]='Subir un nivel en la estructura de carpetas ';respuestas[n]='cd ..';n++;
preguntas[n]='Cambiar a la unidad d: ';respuestas[n]='cd d:';n++;
preguntas[n]='Cambiar a una subcarpeta (llamada <b>instituto</b>) de la carpeta actual ';respuestas[n]='cd instituto';n++;
preguntas[n]='Cambiar a una subcarpeta llamada <b>mis apuntes</b> que se encuentra en <b>instituto</b> ';respuestas[n]='cd instituto/"mis apuntes"';n++;
preguntas[n]='Mostrar la versión de Windows (una vez dentro de la consola) ';respuestas[n]='cmd';n++;
preguntas[n]='Listar archivos y carpetas del directorio actual ';respuestas[n]='dir';n++;
preguntas[n]='Listar archivos por pantallas ';respuestas[n]='dir /p';n++;
preguntas[n]='Listar archivos en formato ancho (directorios entre corchetes) ';respuestas[n]='dir /w';n++;
preguntas[n]='Listar sólo nombres de archivos ';respuestas[n]='dir /b';n++;
preguntas[n]='Listar todos los archivos incluyendo subcarpetas ';respuestas[n]='dir /s';n++;
preguntas[n]='Atajo para cancelar la ejecución de un comando (como el anterior) ';respuestas[n]='Ctrl + C';n++;
preguntas[n]='Listar archivos ocultos ';respuestas[n]='dir /a:h';n++;
preguntas[n]='Listar sólo carpetas ';respuestas[n]='dir /ad';n++;
preguntas[n]='Listar archivos de solo lectura ';respuestas[n]='dir /a:r';n++;
preguntas[n]='Listar archivos de sistema ';respuestas[n]='dir /a:s';n++;
preguntas[n]='Ordenar listado por nombre ';respuestas[n]='dir /o:n';n++;
preguntas[n]='Ordenar listado por fecha ';respuestas[n]='dir /o:d';n++;
preguntas[n]='Ordenar listado por tamaño ';respuestas[n]='dir /o:s';n++;
preguntas[n]='Listar todos los archivos en todas las subcarpetas, en formato simple y ordenados por nombre ';respuestas[n]='dir /s /b /o:n';n++;
preguntas[n]='Crear una carpeta nueva llamada <b>carpetanueva</b> dentro de la carpeta actual ';respuestas[n]='md carpetanueva';n++;
preguntas[n]='Crear una carpeta nueva llamada <b>otra</b> dentro de <b>carpetanueva</b> ';respuestas[n]='md carpetanueva/otra';n++;
preguntas[n]='Eliminar una carpeta vacía llamada <b>carpetanueva</b> ';respuestas[n]='rd carpetaNueva';n++;
preguntas[n]='Eliminar un archivo llamado <b>archivo.txt</b> ';respuestas[n]='del archivo.txt';n++;
preguntas[n]='Eliminar el archivo anterior pidiendo confirmación ';respuestas[n]='del /p archivo.txt';n++;
preguntas[n]='Copiar un archivo llamado <b>archivo.txt</b> a una carpeta llamada <b>carpetanueva</b> ';respuestas[n]='copy archivo.txt carpetanueva';n++;
preguntas[n]='Copiar todos los archivos .txt a otra carpeta llamada <b>carpetanueva</b> ';respuestas[n]='copy *.txt carpetanueva';n++;
preguntas[n]='Mover un archivo llamado <b>archivo.txt</b> a otra carpeta llamada <b>carpetanueva</b> ';respuestas[n]='move archivo.txt carpetanueva';n++;
preguntas[n]='Cambiar el nombre de un archivo llamado <b>archivo.txt</b> y llamarlo <b>archivo2.txt</b> ';respuestas[n]='ren archivo1.txt archivo2.txt';n++;
preguntas[n]='Mostrar contenido de un archivo de texto llamado <b>archivo.txt</b> ';respuestas[n]='type archivo.txt';n++;
preguntas[n]='Mostrar ayuda general de comandos ';respuestas[n]='help';n++;
preguntas[n]='Mostrar ayuda de <b>dir</b> (usando el comando anterior) ';respuestas[n]='help dir';n++;
preguntas[n]='Mostrar ayuda de <b>dir</b> (alternativo) ';respuestas[n]='dir /?';n++;
preguntas[n]='Mostrar ayuda de <b>color</b> (mismo método que en la cuestión anterior) ';respuestas[n]='color /?';n++;
preguntas[n]='Cambiar el color de la consola a fondo negro, texto blanco ';respuestas[n]='color 0f';n++;
preguntas[n]='Cambiar el color de la consola a fondo azul, texto amarillo ';respuestas[n]='color 1e';n++;
preguntas[n]='Cambiar el color de la consola a fondo verde, texto negro ';respuestas[n]='color 2f';n++;
preguntas[n]='Cambiar el color de la consola a fondo rojo, texto blanco ';respuestas[n]='color 4f';n++;
preguntas[n]='Cambiar el color de la consola a fondo morado, texto blanco ';respuestas[n]='color 5f';n++;
preguntas[n]='Cambiar el color de la consola a fondo cian, texto negro ';respuestas[n]='color 3f';n++;
preguntas[n]='Cambiar el color de la consola a fondo amarillo, texto azul ';respuestas[n]='color e1';n++;
preguntas[n]='Cambiar el color de la consola a fondo gris, texto rojo ';respuestas[n]='color 7c';n++;
preguntas[n]='Cambiar el color de la consola a fondo blanco, texto negro ';respuestas[n]='color f0';n++;
preguntas[n]='Cambiar el color de la consola a fondo negro, texto verde ';respuestas[n]='color 0a';n++;
preguntas[n]='Cambiar el color de la consola a fondo negro, texto rojo ';respuestas[n]='color 0c';n++;
preguntas[n]='Cambiar el color de la consola a fondo azul, texto blanco ';respuestas[n]='color 1f';n++;
preguntas[n]='Cambiar el color de la consola a fondo verde, texto blanco ';respuestas[n]='color 2f';n++;
preguntas[n]='Cambiar el color de la consola a fondo rojo, texto amarillo ';respuestas[n]='color 4e';n++;
preguntas[n]='Cambiar el color de la consola a fondo azul, texto amarillo ';respuestas[n]='color 1e';n++;
preguntas[n]='Cambiar el color de la consola a fondo verde, texto amarillo ';respuestas[n]='color 2e';n++;
preguntas[n]='Cambiar el color de la consola a fondo rojo, texto azul ';respuestas[n]='color 4b';n++;
preguntas[n]='Abre el Panel de control ';respuestas[n]='control';n++;
preguntas[n]='Abre las Opciones de carpeta (Ver/Ocultar archivos y carpetas) ';respuestas[n]='control folders';n++;
preguntas[n]='Abre el Administrador de tareas ';respuestas[n]='taskmgr';n++;
preguntas[n]='Abre el Editor del registro ';respuestas[n]='regedit';n++;
preguntas[n]='Abre la Configuración del sistema (msconfig) ';respuestas[n]='msconfig';n++;
preguntas[n]='Abre el Visor de eventos ';respuestas[n]='eventvwr';n++;
preguntas[n]='Abre el Administrador de dispositivos ';respuestas[n]='devmgmt.msc';n++;
preguntas[n]='Abre el Monitor de recursos ';respuestas[n]='resmon';n++;
preguntas[n]='Abre el Programador de tareas ';respuestas[n]='taskschd.msc';n++;
preguntas[n]='Abre Windows PowerShell ';respuestas[n]='powershell';n++;
preguntas[n]='Abre el Explorador de archivos ';respuestas[n]='explorer';n++;
preguntas[n]='Abre las Propiedades del sistema ';respuestas[n]='sysdm.cpl';n++;
preguntas[n]='Abre la Configuración de red ';respuestas[n]='ncpa.cpl';n++;
preguntas[n]='Abre la Configuración de sonido ';respuestas[n]='mmsys.cpl';n++;
preguntas[n]='Abre la Configuración de fecha y hora ';respuestas[n]='timedate.cpl';n++;
preguntas[n]='Abre la Configuración de usuario (cuentas) ';respuestas[n]='control userpasswords2';n++;
preguntas[n]='Abre la Visor de Directiva de Seguridad Local ';respuestas[n]='secpol.msc';n++;
preguntas[n]='Abre el Administrador de discos ';respuestas[n]='diskmgmt.msc';n++;
preguntas[n]='Abre la Conexión a Escritorio Remoto ';respuestas[n]='mstsc';n++;
preguntas[n]='Abre el Administrador de servicios ';respuestas[n]='services.msc';n++;
preguntas[n]='Abre el Firewall de Windows ';respuestas[n]='firewall.cpl';n++;
preguntas[n]='Abre la Configuración de Idioma e idioma de teclado ';respuestas[n]='intl.cpl';n++;
preguntas[n]='Abre la Configuración de Energía ';respuestas[n]='powercfg.cpl';n++;
preguntas[n]='Abre el Centro de Accesibilidad ';respuestas[n]='utilman';n++;
preguntas[n]='Abre el Administrador de credenciales ';respuestas[n]='control /name Microsoft.CredentialManager';n++;
preguntas[n]='Abre el Centro de redes y recursos compartidos ';respuestas[n]='control /name Microsoft.NetworkAndSharingCenter';n++;
preguntas[n]='Abre el Administrador de dispositivos de sonido y audio ';respuestas[n]='sndvol';n++;
preguntas[n]='Abre la Configuración de fuentes de Windows ';respuestas[n]='start fonts';n++;
preguntas[n]='<br><b>Las cuestiones siguientes no corresponden a comandos. Son acciones comunes ejecutables desde la consola</b><br>Acceso al Bloc de Notas ';respuestas[n]='notepad';n++;
preguntas[n]='Abre el Bloc de notas para crear o editar un archivo llamado <b>archivo.txt</b> ';respuestas[n]='notepad archivo.txt';n++;
preguntas[n]='Abre Paint y carga una imagen llamada <b>dibujo.png</b> ';respuestas[n]='mspaint dibujo.png';n++;
preguntas[n]='Abre Paint y crea un nuevo archivo, sin especificar nombre ';respuestas[n]='mspaint';n++;
preguntas[n]='Abre WordPad para crear un archivo nuevo ';respuestas[n]='write';n++;
preguntas[n]='Abre la calculadora de Windows ';respuestas[n]='calc';n++;
preguntas[n]='Abre WordPad para editar un documento llamado <b>documento.rtf</b> ';respuestas[n]='write documento.rtf';n++;
preguntas[n]='Abre el Explorador de archivos en la carpeta <b>Descargas</b> (Desde cualquier ubicación en tu perfil de Windows) ';respuestas[n]='explorer c:/users/"curso 2025"/downloads';n++;
preguntas[n]='Abre Microsoft Edge en la página de Google ';respuestas[n]='start msedge https://www.google.com';n++;
preguntas[n]='Abre el Reproductor de Windows Media para reproducir <b>canción.mp3</b> (si está instalado) ';respuestas[n]='wmplayer canción.mp3';n++;
preguntas[n]='Abre la aplicación de Fotos para ver <b>imagen.png</b>  (Desde cualquier ubicación en tu perfil de Windows) ';respuestas[n]='start c:/users/"curso 2025"/pictures/imagen.png';n++;
preguntas[n]='Abre Google Chrome (si está instalado) en la página del IES Padre Suárez ';respuestas[n]='start chrome https://www.iespadresuarez.es';n++;
